# path: ./btcts_next/src/btcts/apps/operator_ui/texts/ai_panels.py
# desc: AI / agent / decision-log / watch-list related Operator UI text keys.

AI_PANELS_TEXTS = {
    "en": {
        "agent_panels_title": "AI Agents",
        "agent_panels_missing_data": "insufficient data for AI agent panels",
        "agent_panels_unavailable": "AI agent data unavailable",
        "agent_panels_snapshot": "Agent Snapshot",

        "agent_analyst_title": "Analyst AI",
        "agent_analyst_regime": "Regime",
        "agent_analyst_spread": "Spread State",
        "agent_analyst_pressure": "Pressure",

        "agent_strategy_title": "Strategy AI",
        "agent_strategy_archetype": "Archetype",
        "agent_strategy_stance": "Stance",
        "agent_strategy_delta": "Trade Delta",

        "agent_risk_title": "Risk AI",
        "agent_risk_level": "Risk Level",
        "agent_risk_latency": "Avg Latency(ms)",
        "agent_risk_wall_ratio": "Wall Ratio",

        "agent_value_range": "RANGE",
        "agent_value_trend": "TREND",
        "agent_value_normal": "NORMAL",
        "agent_value_wide": "WIDE",
        "agent_value_tight": "TIGHT",
        "agent_value_neutral": "NEUTRAL",
        "agent_value_buy": "BUY",
        "agent_value_sell": "SELL",
        "agent_value_wait": "WAIT",
        "agent_value_prepare": "PREPARE",
        "agent_value_long_bias": "LONG BIAS",
        "agent_value_short_bias": "SHORT BIAS",
        "agent_value_observe": "observe",
        "agent_value_breakout": "breakout",
        "agent_value_liquidity_trap": "liquidity_trap",
        "agent_value_mean_reversion": "mean_reversion",
        "agent_value_momentum_probe": "momentum_probe",
        "agent_value_low": "LOW",
        "agent_value_medium": "MEDIUM",
        "agent_value_high": "HIGH",

        "ai_operator_title": "AI Operator",
        "ai_operator_missing_data": "AI Operator data is not available.",
        "ai_operator_action": "Suggested Action",
        "ai_operator_risk": "Risk Posture",
        "ai_operator_mode": "AI Mode",
        "ai_operator_prompt": "Summarize the current market state and suggest the best operator action.",
        "ai_operator_action_long_watch": "LONG WATCH",
        "ai_operator_action_short_watch": "SHORT WATCH",
        "ai_operator_action_trap_caution": "TRAP CAUTION",
        "ai_operator_action_wait": "WAIT",
        "ai_operator_risk_low": "LOW",
        "ai_operator_risk_medium": "MEDIUM",
        "ai_operator_risk_high": "HIGH",
        "ai_operator_send_to_replay": "Send to Replay",
        "ai_operator_open_research": "Open Research",
        "ai_operator_ask_ai_why": "Ask AI Why",
        "ai_operator_mark_as_watch": "Mark as Watch",
        "ai_operator_watch_saved": "Watch item saved.",
        "ai_operator_live_local_prefix": "local AI mode active: generating a local summary based on live_canonical",
        "ai_operator_tactic_stance_title": "Tactic stance proposal",
        "ai_operator_tactic_stance_support": "Supporting operating-stance context only. Not an execution instruction.",
        "ai_operator_tactic_interpretation_support": "Interpret the following lines as review support only, not as an automatic decision.",
        "ai_operator_tactic_interpretation_prefix": "Interpretation",
        "ai_operator_advisory_support": "advisory support context prepared (supporting context only, not final decision)",
        "ai_operator_prediction_snapshot_title": "Prediction snapshot",
        "tactic_stance_label_operating_stance": "Operating Stance",
        "tactic_stance_label_scenario_regime": "Scenario Regime",
        "tactic_stance_label_proposal_state": "Proposal State",
        "tactic_stance_label_profile_kind": "Profile Kind",
        "tactic_stance_label_review_needed": "Review Needed",
        "tactic_stance_label_rollback_ready": "Rollback Ready",
        "tactic_stance_label_adoption_ready": "Adoption Ready",
        "tactic_stance_label_rollback_target_available": "Rollback Target Available",
        "tactic_stance_label_selected_set_id": "Selected Set ID",
        "tactic_stance_label_rollback_target_ref": "Rollback Target Ref",
        "tactic_stance_label_comparison_relation": "Comparison Relation",
        "tactic_stance_label_overlay_influence": "Overlay Influence",
        "tactic_stance_label_selection_bias_tags": "Selection Bias Tags",
        "tactic_stance_value_true": "Yes",
        "tactic_stance_value_false": "No",

        "watch_list_title": "Watch List",
        "watch_list_empty": "No watch items yet.",
        "watch_list_remove": "Remove",
        "watch_list_clear_all": "Clear All",
        "watch_list_replay": "Replay",
        "watch_list_research": "Research",
        "watch_list_persist_failed": "Watch persistence failed. Showing session-only items.",
        "watch_list_storage_path": "Storage Path",
        "watch_list_storage_state": "Storage State",

        "decision_log_title": "AI Operator Decision Log",
        "decision_log_empty": "No AI operator decisions yet.",
        "decision_log_replay": "Replay",
        "decision_log_research": "Research",
        "decision_log_remove": "Remove",
        "decision_log_clear_all": "Clear All",
        "decision_log_persist_failed": "Decision log persistence failed. Showing session-only items.",
        "decision_log_storage_path": "Storage Path",
        "decision_log_storage_state": "Storage State",
        "decision_log_watch": "Watch",
        "decision_log_watch_added": "Added to Watch List",
    },
    "ja": {
        "agent_panels_title": "AIエージェント",
        "agent_panels_missing_data": "AIエージェント表示に必要なデータが不足しています",
        "agent_panels_unavailable": "AIエージェントのデータを取得できません",
        "agent_panels_snapshot": "エージェントスナップショット",

        "agent_analyst_title": "Analyst AI",
        "agent_analyst_regime": "地合い",
        "agent_analyst_spread": "スプレッド状態",
        "agent_analyst_pressure": "圧力",

        "agent_strategy_title": "Strategy AI",
        "agent_strategy_archetype": "アーキタイプ",
        "agent_strategy_stance": "スタンス",
        "agent_strategy_delta": "約定デルタ",

        "agent_risk_title": "Risk AI",
        "agent_risk_level": "リスク水準",
        "agent_risk_latency": "平均レイテンシ(ms)",
        "agent_risk_wall_ratio": "壁比率",

        "agent_value_range": "レンジ",
        "agent_value_trend": "トレンド",
        "agent_value_normal": "通常",
        "agent_value_wide": "広い",
        "agent_value_tight": "狭い",
        "agent_value_neutral": "中立",
        "agent_value_buy": "買い",
        "agent_value_sell": "売り",
        "agent_value_wait": "待機",
        "agent_value_prepare": "準備",
        "agent_value_long_bias": "ロング寄り",
        "agent_value_short_bias": "ショート寄り",
        "agent_value_observe": "観察",
        "agent_value_breakout": "ブレイクアウト",
        "agent_value_liquidity_trap": "流動性トラップ",
        "agent_value_mean_reversion": "平均回帰",
        "agent_value_momentum_probe": "モメンタム探索",
        "agent_value_low": "低",
        "agent_value_medium": "中",
        "agent_value_high": "高",

        "ai_operator_title": "AI Operator",
        "ai_operator_missing_data": "AI Operator に必要なデータがありません。",
        "ai_operator_action": "推奨アクション",
        "ai_operator_risk": "リスク姿勢",
        "ai_operator_mode": "AIモード",
        "ai_operator_prompt": "現在の市場状態を要約し、最適なオペレーター行動を提案してください。",
        "ai_operator_action_long_watch": "ロング監視",
        "ai_operator_action_short_watch": "ショート監視",
        "ai_operator_action_trap_caution": "トラップ警戒",
        "ai_operator_action_wait": "待機",
        "ai_operator_risk_low": "低",
        "ai_operator_risk_medium": "中",
        "ai_operator_risk_high": "高",
        "ai_operator_send_to_replay": "Replayへ送る",
        "ai_operator_open_research": "Researchを開く",
        "ai_operator_ask_ai_why": "AIに理由を聞く",
        "ai_operator_mark_as_watch": "Watchに追加",
        "ai_operator_watch_saved": "監視項目として保存しました。",
        "ai_operator_live_local_prefix": "local AI mode active: live_canonical を基にローカル要約を生成しています",
        "ai_operator_tactic_stance_title": "戦術スタンス提案",
        "ai_operator_tactic_stance_support": "これは執行指示ではなく、運用上の構えを補助的に示す文脈です。",
        "ai_operator_tactic_interpretation_support": "以下の行はレビュー補助の解釈であり、自動判断ではありません。",
        "ai_operator_tactic_interpretation_prefix": "解釈",
        "ai_operator_advisory_support": "advisory 補助文脈を準備しました（最終判断ではありません）",
        "ai_operator_prediction_snapshot_title": "予測スナップショット",
        "tactic_stance_label_operating_stance": "運用スタンス",
        "tactic_stance_label_scenario_regime": "シナリオ地合い",
        "tactic_stance_label_proposal_state": "提案状態",
        "tactic_stance_label_profile_kind": "プロファイル種別",
        "tactic_stance_label_review_needed": "レビュー要否",
        "tactic_stance_label_rollback_ready": "ロールバック準備",
        "tactic_stance_label_adoption_ready": "採用候補状態",
        "tactic_stance_label_rollback_target_available": "ロールバック先の有無",
        "tactic_stance_label_selected_set_id": "選択セットID",
        "tactic_stance_label_rollback_target_ref": "ロールバック先セット",
        "tactic_stance_label_comparison_relation": "比較関係",
        "tactic_stance_label_overlay_influence": "オーバーレイ影響",
        "tactic_stance_label_selection_bias_tags": "選択バイアスタグ",
        "tactic_stance_value_true": "はい",
        "tactic_stance_value_false": "いいえ",

        "watch_list_title": "Watch List",
        "watch_list_empty": "まだ watch 項目はありません。",
        "watch_list_remove": "削除",
        "watch_list_clear_all": "全削除",
        "watch_list_replay": "Replay",
        "watch_list_research": "Research",
        "watch_list_persist_failed": "Watch の永続化に失敗しました。session 内表示のみです。",
        "watch_list_storage_path": "保存先",
        "watch_list_storage_state": "保存状態",

        "decision_log_title": "AI Operator Decision Log",
        "decision_log_empty": "まだ AI Operator の判断履歴はありません。",
        "decision_log_replay": "Replay",
        "decision_log_research": "Research",
        "decision_log_remove": "削除",
        "decision_log_clear_all": "全削除",
        "decision_log_persist_failed": "Decision Log の永続化に失敗しました。session 内表示のみです。",
        "decision_log_storage_path": "保存先",
        "decision_log_storage_state": "保存状態",
        "decision_log_watch": "Watch",
        "decision_log_watch_added": "Added to Watch List",
    },
}