# path: ./btcts_next/src/btcts/apps/operator_ui/texts/collector.py
# desc: Collector page and live operations related text keys for Operator UI.

COLLECTOR_TEXTS = {
    "en": {
        "collector_title": "Collector Status",
        "collector_metric_status": "Collector",
        "collector_metric_exchange": "Exchange",
        "collector_metric_feed": "Feed",
        "collector_metric_eps": "Events/sec",
        "collector_status_running": "Running",
        "collector_status_connected": "Connected",
        "collector_status_live": "Live",
        "collector_recent_events": "Recent Events (WarRoom View)",
        "collector_no_events": "No events yet",
        "collector_note_sequence": "note=last_sequence_id shows the final sequence within one smoke cycle (not a global sequence)",
        "collector_page_caption": "This page shows current live operation status and weekly-test readiness items based on Collector vNext state / health / checkpoint / audit.",
        "collector_audit_empty": "No live audit events yet.",
        "event_col_time": "Time",
        "event_col_event": "Event",
        "event_col_exchange": "Exchange",
        "event_col_topic": "Topic",
        "event_col_latency": "Latency(ms)",
        "event_col_bytes": "Bytes",
        "system_stats_title": "System Stats",
        "execution_feed_title": "Execution Feed",
        "execution_feed_empty": "No recent execution feed events.",
        "execution_feed_total": "Total Events",
        "execution_feed_avg_latency": "Avg Latency(ms)",
        "execution_feed_max_latency": "Max Latency(ms)",
        "execution_feed_status": "Feed Status",
        "execution_feed_orderbook": "Orderbook Events",
        "execution_feed_trades": "Trade Events",
        "execution_feed_rate_hold": "Rate Hold",
        "execution_feed_load": "Processing Load",
        "execution_feed_latest": "Latest Event",

        "execution_feed_rate_hold": "Rate Hold Events",
    },
    "ja": {
        "collector_title": "Collector 状態",
        "collector_metric_status": "Collector",
        "collector_metric_exchange": "取引所",
        "collector_metric_feed": "Feed",
        "collector_metric_eps": "イベント/秒",
        "collector_status_running": "稼働中",
        "collector_status_connected": "接続中",
        "collector_status_live": "LIVE",
        "collector_recent_events": "最新イベント（WarRoom表示）",
        "collector_no_events": "イベントはまだありません",
        "collector_note_sequence": "note=last_sequence_id は smoke 1サイクル内の最終 sequence を示します（global sequence ではありません）",
        "collector_page_caption": "このページは Collector vNext の state / health / checkpoint / audit を基に、現在の live 運転状態と週間テスト前に必要な観測項目を表示します。",
        "collector_audit_empty": "live audit event がまだありません。",
        "event_col_time": "時刻",
        "event_col_event": "イベント",
        "event_col_exchange": "取引所",
        "event_col_topic": "トピック",
        "event_col_latency": "レイテンシ(ms)",
        "event_col_bytes": "Bytes",
        "system_stats_title": "システム統計",
        "execution_feed_title": "Execution Feed",
        "execution_feed_empty": "直近の Execution Feed イベントがありません。",
        "execution_feed_total": "総イベント数",
        "execution_feed_avg_latency": "平均レイテンシ(ms)",
        "execution_feed_max_latency": "最大レイテンシ(ms)",
        "execution_feed_status": "Feed状態",
        "execution_feed_orderbook": "Orderbook件数",
        "execution_feed_trades": "Trades件数",
        "execution_feed_rate_hold": "Rate Hold件数",
        "execution_feed_load": "処理負荷",
        "execution_feed_latest": "最新イベント",

        "execution_feed_rate_hold": "Rate Hold件数",
    },
}