# path: ./btcts_next/src/btcts/apps/operator_ui/texts/collector.py
# desc: Collector page and live operations related text keys for Operator UI.

COLLECTOR_TEXTS = {
    "en": {
        "collector_title": "Collector Status",
        "collector_metric_status": "Collector",
        "collector_metric_exchange": "Exchange",
        "collector_metric_feed": "Feed",
        "collector_metric_eps": "Events/sec",
        "collector_status_running": "Running",
        "collector_status_connected": "Connected",
        "collector_status_live": "Live",
        "collector_recent_events": "Recent Events (WarRoom View)",
        "collector_no_events": "No events yet",
        "collector_note_sequence": "note=last_sequence_id shows the final sequence within one smoke cycle (not a global sequence)",
        "collector_page_caption": "This page shows current live operation status and weekly-test readiness items based on Collector vNext state / health / checkpoint / audit.",
        "collector_audit_empty": "No live audit events yet.",
        "event_col_time": "Time",
        "event_col_event": "Event",
        "event_col_exchange": "Exchange",
        "event_col_topic": "Topic",
        "event_col_latency": "Latency(ms)",
        "event_col_bytes": "Bytes",
        "system_stats_title": "System Stats",
        "execution_feed_title": "Execution Feed",
        "execution_feed_empty": "No recent execution feed events.",
        "execution_feed_total": "Total Events",
        "execution_feed_avg_latency": "Avg Latency(ms)",
        "execution_feed_max_latency": "Max Latency(ms)",
        "execution_feed_status": "Feed Status",
        "execution_feed_orderbook": "Orderbook Events",
        "execution_feed_trades": "Trade Events",
        "execution_feed_rate_hold": "Rate Hold Events",
        "execution_feed_load": "Processing Load",
        "execution_feed_latest": "Latest Event",
        "collector_button_start_unified": "Start",
        "collector_button_safe_stop_unified": "Safe Stop",
        "collector_button_restart_unified": "Restart",
        "collector_msg_start_request_accepted": "start accepted: {message}",
        "collector_msg_start_request_failed": "start failed: {message}",
        "collector_msg_start_already_running": "already running: {message}",
        "collector_msg_safe_stop_pending": "safe stop request is already pending. wait for watchdog orchestration to finish.",
        "collector_msg_safe_stop_request_accepted": "safe stop accepted: {message}",
        "collector_msg_safe_stop_request_failed": "safe stop failed: {message}",
        "collector_msg_restart_pending": "restart request is already pending. wait for watchdog to consume it before reissuing.",
        "collector_msg_restart_request_accepted": "restart accepted: {message}",
        "collector_msg_restart_request_failed": "restart failed: {message}",
        "collector_msg_watchdog_not_running": "watchdog is not RUNNING. request file can be written, but restart may not execute yet.",
        "collector_msg_stack_not_running": "stack is not active. press Start to launch watchdog and archive worker.",
        "collector_msg_supervisor_status_unavailable": "unified supervisor status not available",
        "collector_metric_supervisor_mode": "Supervisor Mode",
        "collector_metric_pending_request": "Pending Request",
        "collector_metric_stack_active": "Stack Active",
        "collector_value_yes": "YES",
        "collector_value_no": "NO",
        "collector_caption_supervisor_health_line": "started_at={started_at} / last_seen_ts={last_seen_ts}",
        "collector_caption_stack_control_line": "stack_active={stack_active} / supervisor_active={supervisor_active} / archive_active={archive_active} / safe_stop_phase={safe_stop_phase} / archive_copy_mode={archive_copy_mode} ({archive_copy_phase}) / archive_gc_mode={archive_gc_mode} ({archive_gc_phase})",
    },
    "ja": {
        "collector_title": "Collector 状態",
        "collector_metric_status": "Collector",
        "collector_metric_exchange": "取引所",
        "collector_metric_feed": "Feed",
        "collector_metric_eps": "イベント/秒",
        "collector_status_running": "稼働中",
        "collector_status_connected": "接続中",
        "collector_status_live": "LIVE",
        "collector_recent_events": "最新イベント（WarRoom表示）",
        "collector_no_events": "イベントはまだありません",
        "collector_note_sequence": "note=last_sequence_id は smoke 1サイクル内の最終 sequence を示します（global sequence ではありません）",
        "collector_page_caption": "このページは Collector vNext の state / health / checkpoint / audit を基に、現在の live 運転状態と週間テスト前に必要な観測項目を表示します。",
        "collector_audit_empty": "live audit event がまだありません。",
        "event_col_time": "時刻",
        "event_col_event": "イベント",
        "event_col_exchange": "取引所",
        "event_col_topic": "トピック",
        "event_col_latency": "レイテンシ(ms)",
        "event_col_bytes": "Bytes",
        "system_stats_title": "システム統計",
        "execution_feed_title": "Execution Feed",
        "execution_feed_empty": "直近の Execution Feed イベントがありません。",
        "execution_feed_total": "総イベント数",
        "execution_feed_avg_latency": "平均レイテンシ(ms)",
        "execution_feed_max_latency": "最大レイテンシ(ms)",
        "execution_feed_status": "Feed状態",
        "execution_feed_orderbook": "Orderbook件数",
        "execution_feed_trades": "Trades件数",
        "execution_feed_rate_hold": "Rate Hold件数",
        "execution_feed_load": "処理負荷",
        "execution_feed_latest": "最新イベント",
        "collector_button_start_unified": "起動",
        "collector_button_safe_stop_unified": "安全停止",
        "collector_button_restart_unified": "再起動",
        "collector_msg_start_request_accepted": "起動を受け付けました: {message}",
        "collector_msg_start_request_failed": "起動に失敗しました: {message}",
        "collector_msg_start_already_running": "すでに起動中です: {message}",
        "collector_msg_safe_stop_pending": "安全停止 request はすでに pending です。watchdog の停止 orchestration 完了を待ってください。",
        "collector_msg_safe_stop_request_accepted": "安全停止を受け付けました: {message}",
        "collector_msg_safe_stop_request_failed": "安全停止に失敗しました: {message}",
        "collector_msg_restart_pending": "restart request はすでに pending です。watchdog が消費するまで再発行は待ってください。",
        "collector_msg_restart_request_accepted": "再起動を受け付けました: {message}",
        "collector_msg_restart_request_failed": "再起動に失敗しました: {message}",
        "collector_msg_watchdog_not_running": "watchdog は RUNNING ではありません。request file は書けますが、restart が実行されない可能性があります。",
        "collector_msg_stack_not_running": "stack は起動していません。起動ボタンで watchdog と archive worker を立ち上げてください。",
        "collector_msg_supervisor_status_unavailable": "unified supervisor status を利用できません",
        "collector_metric_supervisor_mode": "Supervisor状態",
        "collector_metric_pending_request": "保留リクエスト",
        "collector_metric_stack_active": "Stack稼働",
        "collector_value_yes": "YES",
        "collector_value_no": "NO",
        "collector_caption_supervisor_health_line": "started_at={started_at} / last_seen_ts={last_seen_ts}",
        "collector_caption_stack_control_line": "stack_active={stack_active} / supervisor_active={supervisor_active} / archive_active={archive_active} / safe_stop_phase={safe_stop_phase} / archive_copy_mode={archive_copy_mode} ({archive_copy_phase}) / archive_gc_mode={archive_gc_mode} ({archive_gc_phase})",
    },
}