# path: ./btcts_next/src/btcts/apps/operator_ui/texts/common.py
# desc: Shared Operator UI text keys used across sidebar, navigation, and common controls.

COMMON_TEXTS = {
    "en": {
        "app_title": "BTC Trade System",
        "app_subtitle": "Project Chimera Operator Console",
        "sidebar_title": "Operator Panel",
        "sidebar_nav": "Navigate",
        "lang_label": "Language",
        "scale_label": "Font Scale",
        "refresh_label": "Widget Auto Refresh",
        "refresh_help": "Controls widget / fragment updates on live pages such as Health and War Room.",
        "refresh_interval_label": "Refresh Interval (sec)",
        "refresh_status_on": "Widget auto refresh ON",
        "refresh_status_off": "Widget auto refresh OFF",
        "page_collector": "Collector",
        "page_health": "Health",
        "page_logs": "Logs",
        "page_config": "Config",
        "page_research": "Research",
        "page_replay": "Replay",
        "page_warroom": "War Room",
        "page_autotrade": "AutoTrade",
        "dashboard_hub_status_title": "ダッシュボードハブ",
        "dashboard_hub_status_caption": "移動とアラートのハブです。表示専用の状態で、市場意味の判定は行いません。",
        "dashboard_hub_selected_page": "選択中ページ",
        "dashboard_hub_refresh": "更新",
        "dashboard_hub_registered_widgets": "登録ウィジェット",
        "dashboard_hub_alert_normal": "ダッシュボードレベルのUIアラートはありません。",
        "dashboard_hub_alert_attention": "ページ内の警告や古いwidget表示があれば確認してください。",
        "dashboard_hub_status_title": "Dashboard Hub",
        "dashboard_hub_status_caption": "Navigation / alert hub; display-only status, not market meaning.",
        "dashboard_hub_selected_page": "Selected Page",
        "dashboard_hub_refresh": "Refresh",
        "dashboard_hub_registered_widgets": "Registered Widgets",
        "dashboard_hub_alert_normal": "No dashboard-level UI alerts.",
        "dashboard_hub_alert_attention": "Check page-level warnings or stale widgets if visible.",
    },
    "ja": {
        "app_title": "BTC Trade System",
        "app_subtitle": "Project Chimera オペレーターコンソール",
        "sidebar_title": "操作パネル",
        "sidebar_nav": "移動",
        "lang_label": "表示言語",
        "scale_label": "文字サイズ",
        "refresh_label": "ウィジェット自動更新",
        "refresh_help": "Health や War Room などのライブページで、widget / fragment の更新を有効にします。",
        "refresh_interval_label": "更新間隔(秒)",
        "refresh_status_on": "ウィジェット自動更新 ON",
        "refresh_status_off": "ウィジェット自動更新 OFF",
        "page_collector": "Collector",
        "page_health": "Health",
        "page_logs": "Logs",
        "page_config": "Config",
        "page_research": "Research",
        "page_replay": "Replay",
        "page_warroom": "War Room",
        "page_autotrade": "AutoTrade",
    },
}
