# path: ./btcts_next/src/btcts/apps/operator_ui/texts/health.py
# desc: System Health ページ専用の表示文言。

HEALTH_TEXTS = {
    "en": {
        "health_title": "System Health",
        "health_summary_collector": "Collector",
        "health_summary_api": "API Rate",
        "health_summary_ws": "WS",
        "health_summary_layer3": "Layer3",
        "health_section_api_limits": "Collector Rate Window",
        "health_section_api_chart": "Collector API Rate",
        "health_section_ws_chart": "WS / Continuity",
        "health_section_layer3_chart": "Layer3 Trust",
        "health_section_recent_events": "Recent Health Events",
        "health_table_ts": "Time",
        "health_table_event": "Event",
        "health_table_topic": "Topic",
        "health_table_reason": "Reason",
        "health_table_exchange": "Exchange",
        "health_event_gap_detected": "gap detected",
        "health_event_resync_started": "resync started",
        "health_event_resync_completed": "resync completed",
        "health_event_exploration_crit": "runtime entered CRIT",
        "health_event_exploration_recovery": "runtime entered RECOVERY",
        "health_event_exploration_warn": "runtime entered WARN",
        "health_event_exploration_normal": "runtime returned to NORMAL",
        "health_event_exploration_request_completed": "runtime request completed",
        "health_event_exploration_request_failed": "runtime request failed",
        "health_event_ws_exec_started": "ws executions started",
        "health_event_ws_exec_connected": "ws executions connected",
        "health_event_ws_exec_reconnected": "ws executions reconnected",
        "health_event_ws_exec_message_received": "ws executions message received",
        "health_event_ws_exec_message_skipped": "ws executions message skipped",
        "health_event_ws_exec_meta": "ws executions meta",
        "health_event_ws_exec_trade_written": "ws executions trade written",
        "health_reason_delta_arrived_before_snapshot": "delta arrived before snapshot",
        "health_reason_snapshot_received_after_gap": "snapshot received after gap",
        "health_table_empty_value": "-",
        "health_section_current_state": "Current State Snapshot",
        "health_section_read_guide": "How to Read This Tab",
        "health_label_range_selector": "Range",
        "health_range_1h": "1h",
        "health_range_24h": "24h",
        "health_range_1w": "1w",
        "health_section_continuity_api": "API Continuity",
        "health_section_continuity_ws": "WS Continuity",
        "health_continuity_caption_api": "Each cell is one minute. This rail shows REST/API-side continuity. Green=steady, Yellow=caution, Orange=unstable, Red=broken, Gray=no data.",
        "health_continuity_caption_ws": "Each cell is one minute. This rail shows WS-side continuity. Green=steady, Yellow=caution, Orange=unstable, Red=broken, Gray=no data.",
        "health_continuity_reason_title": "Current Continuity Reason",
        "health_continuity_reason_none": "No active warning.",
        "health_continuity_reason_steady": "steady / ws live",
        "health_continuity_reason_resync_recovered": "resync recovered",
        "health_continuity_reason_syncing": "ws syncing / connecting",
        "health_continuity_reason_gap_single": "single gap observed",
        "health_continuity_reason_gap_repeated": "repeated gap observed",
        "health_continuity_reason_warn_error": "warn/error observed",
        "health_continuity_reason_no_data": "no audit activity",
        "health_continuity_reason_health_not_ok": "collector health not ok",
        "health_continuity_reason_ws_not_live": "ws not live",
        "health_continuity_level_green": "steady",
        "health_continuity_level_yellow": "caution",
        "health_continuity_level_orange": "unstable",
        "health_continuity_level_red": "broken",
        "health_continuity_level_gray": "no data",
        "health_read_guide_line1": "Collector / API / WS should stay healthy or caution, not broken.",
        "health_read_guide_line2": "Layer3 is the main weekly-test target. trusted is healthy, provisional is caution, broken is risk.",
        "health_read_guide_line3": "Gap / resync / 429 spikes are important when they repeat, not as single noise.",
        "health_chart_api_caption": "Read this as collector request pressure. The upper chart is audit-based activity estimation, while the lower overlay uses exploration rate state as the current source of truth for utilization, target ratio, and hard cap. 429 is shown as a marker-like signal.",
        "health_chart_ws_caption": "Read this as WS continuity. Repeated gap/resync spikes mean continuity is unstable.",
        "health_chart_layer3_caption": "Read this as Layer3 confidence monitor. A flat low score means trust is not established yet.",
        "health_chart_unfinished_bucket_caption": "The rightmost in-progress bucket is excluded from the normal chart because it is not finalized yet.",
        "health_chart_api_long_range_caption": "For 24h / 1w ranges, event-based indicators are shown instead of 5-minute indicators so that the scale keeps the same meaning.",
        "health_chart_api_overlay_current_only_caption": "For 24h / 1w ranges, the lower rate overlay is treated as a current rate-state summary, not a historical line.",
        "health_chart_api_overlay_current_only_short_caption": "For 24h / 1w ranges, the lower panel shows only the current rate-state summary, not a time-series line.",
        "health_chart_layer3_current_only_caption": "For 24h / 1w ranges, Layer3 is shown mainly as a current evaluation summary rather than a historical line.",
        "health_metric_status": "Status",
        "health_metric_req_1m": "Req / 1m",
        "health_metric_req_5m": "Req / 5m",
        "health_metric_req_snapshot_1m": "Snapshot / 1m",
        "health_metric_req_trades_1m": "Trades / 1m",
        "health_metric_limit_5m": "Limit / 5m",
        "health_metric_wait_ms": "Exploration Mode",
        "health_metric_util_ratio": "Util Ratio",
        "health_metric_last_429": "Last 429",
        "health_metric_hold_until": "Hold Until",
        "health_metric_ws_state": "WS State",
        "health_metric_ws_last_update": "WS Last Update",
        "health_metric_ws_age_sec": "WS Age (sec)",
        "health_metric_ws_events_1m": "WS / 1m",
        "health_metric_gap_1m": "gap / 1m",
        "health_metric_resync_1m": "resync / 1m",
        "health_label_ws_board_exec_section": "WS Board / Executions",
        "health_warning_missing_slot_registrations_prefix": "missing health slot registrations: ",
        "health_warning_unexpected_zone_ids_prefix": "unexpected health zone ids: ",
        "health_metric_ws_freshness": "WS Freshness",
        "health_metric_snapshot_to_live": "Snapshot→LIVE(ms)",
        "health_metric_resync": "Active Target Ratio",
        "health_metric_last_sequence_id": "Last Sequence ID",
        "health_metric_daemon_status": "Daemon Status",
        "health_metric_daemon_last_error": "Daemon Last Error",
        "health_metric_daemon_failures": "Daemon Failures",
        "health_metric_daemon_last_success": "Daemon Last Success",
        "health_metric_trust_state": "Trust",
        "health_metric_continuity_state": "Continuity",
        "health_metric_freshness": "Freshness",
        "health_metric_boundary_reason": "Boundary",
        "health_metric_interpretation": "Interpretation",
        "health_chart_api_events": "collector req/min",
        "health_chart_api_rolling_5m": "collector req / 5m",
        "health_chart_api_limit_5m": "private limit / 5m",
        "health_chart_429_events": "429 marker",
        "health_chart_ws_events": "WS events/min",
        "health_chart_gap_events": "gap/min",
        "health_chart_resync_events": "resync/min",
        "health_chart_warn_error_events": "warn+error/min",
        "health_chart_avg_latency_ms": "avg latency(ms)",
        "health_chart_official_max_rps": "official max rps",
        "health_chart_internal_safe_max_rps": "internal safe max rps",
        "health_chart_eff_max_rps": "effective max rps",
        "health_chart_trust_score": "trust score",
        "health_metric_budget_60s": "Budget / 60s",
        "health_metric_budget_300s": "Budget / 300s",
        "health_metric_target_ratio": "Target Ratio",
        "health_metric_hard_cap_ratio": "Hard Cap",
        "health_chart_current_utilization": "Current Utilization",
        "health_chart_active_target_ratio": "Active Target Ratio",
        "health_chart_target_utilization": "Target Utilization",
        "health_chart_hard_cap_utilization": "Hard Cap Utilization",
        "health_chart_continuity_score": "continuity score",
        "health_chart_interpretation_score": "interpretation score",
        "health_chart_freshness_score": "freshness score",
        "health_label_runtime_wiring": "runtime wiring",
        "health_label_observer_field": "observer field",
        "health_label_summary_field": "summary field",
        "health_label_source_series": "source series",
        "health_label_orderbook_wiring": "orderbook wiring",
        "health_label_present_count": "present",
        "health_label_near_wall": "near wall",
        "health_label_support": "support",
        "health_label_resistance": "resistance",
        "health_label_persistence": "persistence",
        "health_label_near_wall_side": "near_wall_side",
        "health_label_support_side": "support_side",
        "health_label_resistance_side": "resistance_side",
        "health_label_persistence_event": "persistence_event",
        "health_label_persistence_side": "persistence_side",
        "health_label_persistence_observable": "persistence_observable",
        "health_label_semantic_observer": "semantic observer",
        "health_label_strong": "strong",
        "health_label_watch": "watch",
        "health_label_tentative": "tentative",
        "health_label_invalid": "invalid",
        "health_caption_runtime_freshness_prefix": "runtime freshness: ",
        "health_caption_orderbook_source_prefix": "orderbook source: ",
        "health_caption_orderbook_freshness_prefix": "orderbook freshness: ",
        "health_caption_semantic_source_prefix": "semantic source: ",
        "health_value_yes": "yes",
        "health_value_no": "no",
        "health_value_no_data": "NO DATA",
        "health_value_healthy": "HEALTHY",
        "health_value_caution": "CAUTION",
        "health_value_broken": "BROKEN",
        "health_value_live": "LIVE",
        "health_value_syncing": "SYNCING",
        "health_value_running": "RUNNING",
        "health_value_degraded": "DEGRADED",
        "health_value_stopped": "STOPPED",
        "health_value_normal_mode": "NORMAL",
        "health_value_warn_mode": "WARN",
        "health_value_recovery_mode": "RECOVERY",
        "health_value_crit_mode": "CRIT",
        "health_value_continuous": "continuous",
        "health_value_disrupted": "disrupted",
        "health_value_live_freshness": "LIVE",
        "health_value_quiet_freshness": "QUIET",
        "health_value_stale_freshness": "STALE",
        "health_value_broken_freshness": "BROKEN",
        "health_value_trusted": "trusted",
        "health_value_provisional": "provisional",
        "health_value_broken_trust": "broken",
        "health_value_allow_structural_use": "allow_structural_use",
        "health_value_observe_only": "observe_only",
        "health_value_none_boundary": "none",
        "health_value_on": "ON",
        "health_value_off": "OFF",
    },
    "ja": {
        "health_title": "System Health",
        "health_summary_collector": "Collector",
        "health_summary_api": "APIレート",
        "health_summary_ws": "WS",
        "health_summary_layer3": "Layer3",
        "health_section_api_limits": "Collector レート窓",
        "health_section_api_chart": "Collector APIレート",
        "health_section_ws_chart": "WS / 連続性",
        "health_section_layer3_chart": "Layer3 信用",
        "health_section_recent_events": "直近ヘルスイベント",
        "health_table_ts": "時刻",
        "health_table_event": "イベント",
        "health_table_topic": "topic",
        "health_table_reason": "理由",
        "health_table_exchange": "exchange",
        "health_event_gap_detected": "gap 検知",
        "health_event_resync_started": "resync 開始",
        "health_event_resync_completed": "resync 完了",
        "health_event_exploration_crit": "runtime が CRIT に遷移",
        "health_event_exploration_recovery": "runtime が RECOVERY に遷移",
        "health_event_exploration_warn": "runtime が WARN に遷移",
        "health_event_exploration_normal": "runtime が NORMAL に復帰",
        "health_event_exploration_request_completed": "runtime request 完了",
        "health_event_exploration_request_failed": "runtime request 失敗",
        "health_event_ws_exec_started": "ws executions 開始",
        "health_event_ws_exec_connected": "ws executions 接続",
        "health_event_ws_exec_reconnected": "ws executions 再接続",
        "health_event_ws_exec_message_received": "ws executions message 受信",
        "health_event_ws_exec_message_skipped": "ws executions message skip",
        "health_event_ws_exec_meta": "ws executions meta",
        "health_event_ws_exec_trade_written": "ws executions trade 書込",
        "health_reason_delta_arrived_before_snapshot": "snapshot 前に delta 到着",
        "health_reason_snapshot_received_after_gap": "gap 後に snapshot 受信",
        "health_table_empty_value": "-",
        "health_section_current_state": "現在状態スナップショット",
        "health_section_read_guide": "このタブの見方",
        "health_label_range_selector": "表示レンジ",
        "health_range_1h": "1時間",
        "health_range_24h": "24時間",
        "health_range_1w": "1週間",
        "health_section_continuity_api": "API連続性",
        "health_section_continuity_ws": "WS連続性",
        "health_continuity_caption_api": "1セル = 1分です。REST/API 側の連続性を見ます。緑=安定、黄=注意、柿=不安定、赤=危険、灰=データなし。",
        "health_continuity_caption_ws": "1セル = 1分です。WS 側の連続性を見ます。緑=安定、黄=注意、柿=不安定、赤=危険、灰=データなし。",
        "health_continuity_reason_title": "現在の連続性理由",
        "health_continuity_reason_none": "現在有効な警告はありません。",
        "health_continuity_reason_steady": "安定 / ws live",
        "health_continuity_reason_resync_recovered": "resync 回復済み",
        "health_continuity_reason_syncing": "ws 同期中 / 接続中",
        "health_continuity_reason_gap_single": "gap 単発",
        "health_continuity_reason_gap_repeated": "gap 反復",
        "health_continuity_reason_warn_error": "warn/error 発生",
        "health_continuity_reason_no_data": "audit 活動なし",
        "health_continuity_reason_health_not_ok": "collector health not ok",
        "health_continuity_reason_ws_not_live": "ws が LIVE ではない",
        "health_continuity_level_green": "安定",
        "health_continuity_level_yellow": "注意",
        "health_continuity_level_orange": "不安定",
        "health_continuity_level_red": "危険",
        "health_continuity_level_gray": "データなし",
        "health_read_guide_line1": "Collector / API / WS は 正常 か 注意 に収まっているかを見ます。危険 は要対応です。",
        "health_read_guide_line2": "週間テストの主戦場は Layer3 です。trusted は正常、provisional は注意、broken は危険寄りです。",
        "health_read_guide_line3": "gap / resync / 429 は単発ではなく、繰り返し増えるかを重視します。",
        "health_chart_api_caption": "collector のAPI圧力を見る欄です。上段は audit ベースの活動推定、下段 overlay は exploration rate state を正本寄り情報として使い、現在利用率・現在目標比率・目標利用率・上限利用率を表示します。429 はマーカー扱いです。",
        "health_chart_ws_caption": "WS連続性を見る欄です。gap / resync の繰り返し増加は continuity 不安定の兆候です。",
        "health_chart_layer3_caption": "Layer3 信用監視欄です。低スコアが横ばいなら、まだ trust が立っていない可能性があります。",
        "health_chart_unfinished_bucket_caption": "右端の進行中セルは未確定のため、このグラフでは通常表示から除外しています。",
        "health_chart_api_long_range_caption": "24時間・1週間レンジでは、5分指標の代わりにレンジ全体で意味が通るイベント系指標を表示しています。",
        "health_chart_api_overlay_current_only_caption": "24時間・1週間レンジでは、rate overlay 下段は履歴線ではなく現在の rate state 要約として扱います。",
        "health_chart_api_overlay_current_only_short_caption": "24時間・1週間レンジでは、下段は時系列ではなく現在の rate state 要約のみ表示しています。",
        "health_chart_layer3_current_only_caption": "24時間・1週間レンジでは、Layer3 は履歴線ではなく現在評価の確認を主目的とします。",
        "health_metric_status": "状態",
        "health_metric_req_1m": "回数/1分",
        "health_metric_req_5m": "回数/5分",
        "health_metric_req_snapshot_1m": "Snapshot/1分",
        "health_metric_req_trades_1m": "Trades/1分",
        "health_metric_limit_5m": "上限/5分",
        "health_metric_wait_ms": "Exploration モード",
        "health_metric_util_ratio": "利用率",
        "health_metric_last_429": "直近429",
        "health_metric_hold_until": "hold解除予定",
        "health_metric_ws_state": "WS状態",
        "health_metric_ws_last_update": "WS最終更新",
        "health_metric_ws_age_sec": "WS経過秒",
        "health_metric_ws_events_1m": "WS/1分",
        "health_metric_gap_1m": "gap/1分",
        "health_metric_resync_1m": "resync/1分",
        "health_label_ws_board_exec_section": "WS Board / Executions",
        "health_warning_missing_slot_registrations_prefix": "missing health slot registrations: ",
        "health_warning_unexpected_zone_ids_prefix": "unexpected health zone ids: ",
        "health_metric_ws_freshness": "WS鮮度",
        "health_metric_snapshot_to_live": "Snapshot→LIVE(ms)",
        "health_metric_resync": "現在目標比率",
        "health_metric_last_sequence_id": "Last Sequence ID",
        "health_metric_daemon_status": "Daemon 状態",
        "health_metric_daemon_last_error": "Daemon 最終エラー",
        "health_metric_daemon_failures": "Daemon 連続失敗",
        "health_metric_daemon_last_success": "Daemon 最終成功",
        "health_metric_trust_state": "Trust",
        "health_metric_continuity_state": "Continuity",
        "health_metric_freshness": "Freshness",
        "health_metric_boundary_reason": "Boundary",
        "health_metric_interpretation": "Interpretation",
        "health_chart_api_events": "collector 回数/分",
        "health_chart_api_rolling_5m": "collector 回数/5分",
        "health_chart_api_limit_5m": "private 上限/5分",
        "health_chart_429_events": "429 マーカー",
        "health_chart_ws_events": "WSイベント/分",
        "health_chart_gap_events": "gap/分",
        "health_chart_resync_events": "resync/分",
        "health_chart_warn_error_events": "warn+error/分",
        "health_chart_avg_latency_ms": "平均レイテンシ(ms)",
        "health_chart_official_max_rps": "公式上限 rps",
        "health_chart_internal_safe_max_rps": "内部安全上限 rps",
        "health_chart_eff_max_rps": "実効上限 rps",
        "health_chart_trust_score": "trust スコア",
        "health_metric_budget_60s": "予算 / 60秒",
        "health_metric_budget_300s": "予算 / 300秒",
        "health_metric_target_ratio": "目標比率",
        "health_metric_hard_cap_ratio": "上限比率",
        "health_chart_current_utilization": "現在利用率",
        "health_chart_active_target_ratio": "現在目標比率",
        "health_chart_target_utilization": "目標利用率",
        "health_chart_hard_cap_utilization": "上限利用率",
        "health_chart_continuity_score": "continuity スコア",
        "health_chart_interpretation_score": "interpretation スコア",
        "health_chart_freshness_score": "freshness スコア",
        "health_label_runtime_wiring": "runtime wiring",
        "health_label_observer_field": "observer field",
        "health_label_summary_field": "summary field",
        "health_label_source_series": "source series",
        "health_label_orderbook_wiring": "orderbook wiring",
        "health_label_present_count": "present",
        "health_label_near_wall": "near wall",
        "health_label_support": "support",
        "health_label_resistance": "resistance",
        "health_label_persistence": "persistence",
        "health_label_near_wall_side": "near_wall_side",
        "health_label_support_side": "support_side",
        "health_label_resistance_side": "resistance_side",
        "health_label_persistence_event": "persistence_event",
        "health_label_persistence_side": "persistence_side",
        "health_label_persistence_observable": "persistence_observable",
        "health_label_semantic_observer": "semantic observer",
        "health_label_strong": "strong",
        "health_label_watch": "watch",
        "health_label_tentative": "tentative",
        "health_label_invalid": "invalid",
        "health_caption_runtime_freshness_prefix": "runtime freshness: ",
        "health_caption_orderbook_source_prefix": "orderbook source: ",
        "health_caption_orderbook_freshness_prefix": "orderbook freshness: ",
        "health_caption_semantic_source_prefix": "semantic source: ",
        "health_value_yes": "yes",
        "health_value_no": "no",
        "health_value_no_data": "データなし",
        "health_value_healthy": "正常",
        "health_value_caution": "注意",
        "health_value_broken": "危険",
        "health_value_live": "LIVE",
        "health_value_syncing": "SYNCING",
        "health_value_running": "稼働中",
        "health_value_degraded": "劣化",
        "health_value_stopped": "停止",
        "health_value_normal_mode": "通常",
        "health_value_warn_mode": "警戒",
        "health_value_recovery_mode": "復帰中",
        "health_value_crit_mode": "制限中",
        "health_value_continuous": "continuous",
        "health_value_disrupted": "disrupted",
        "health_value_live_freshness": "LIVE",
        "health_value_quiet_freshness": "QUIET",
        "health_value_stale_freshness": "STALE",
        "health_value_broken_freshness": "停止疑い",
        "health_value_trusted": "trusted",
        "health_value_provisional": "provisional",
        "health_value_broken_trust": "broken",
        "health_value_allow_structural_use": "allow_structural_use",
        "health_value_observe_only": "observe_only",
        "health_value_none_boundary": "none",
        "health_value_on": "ON",
        "health_value_off": "OFF",
    },
}