# path: ./btcts_next/src/btcts/apps/operator_ui/texts/research_replay.py
# desc: Research / Replay related Operator UI text keys.

RESEARCH_REPLAY_TEXTS = {
    "en": {
        "research_title": "Research Lab",
        "research_subtitle": "Explore short-term market memory, latency trend, and collector storage status.",
        "research_tab_memory": "Market Memory",
        "research_tab_latency": "Latency",
        "research_tab_storage": "Storage",
        "research_memory_title": "Market Memory History",
        "research_memory_empty": "No persisted market memory yet.",
        "research_memory_spread": "Spread",
        "research_memory_imbalance": "Imbalance",
        "research_memory_delta": "Delta",
        "research_memory_wall_ratio": "Wall Ratio",
        "research_latency_title": "Latency Trend",
        "research_latency_empty": "No latency rows available.",
        "research_latency_avg": "Avg Latency(ms)",
        "research_latency_max": "Max Latency(ms)",
        "research_latency_count": "Latency Rows",
        "research_storage_title": "Collector Storage Snapshot",
        "research_storage_orderbook": "Orderbook",
        "research_storage_trades": "Trades",
        "research_storage_file_count": "File Count",
        "research_storage_latest_file": "Latest File",
        "research_storage_latest_size": "Latest Size(MB)",
        "research_tactic_stance_summary_title": "Tactic stance summary",

        "replay_title": "Replay Lab",
        "replay_subtitle": "Review recent audit events and market memory as the foundation of future replay workflows.",
        "replay_tab_events": "Events",
        "replay_tab_memory": "Market Memory",
        "replay_tab_future": "Future Replay",
        "replay_events_title": "Recent Audit Events",
        "replay_events_empty": "No replayable events available.",
        "replay_events_count": "Event Count",
        "replay_events_avg_latency": "Avg Latency(ms)",
        "replay_events_max_latency": "Max Latency(ms)",
        "replay_memory_title": "Persisted Market Memory",
        "replay_memory_empty": "No persisted market memory available.",
        "replay_future_title": "Replay Roadmap",
        "replay_future_desc": "This space will evolve into a full replay workflow.",
        "replay_future_item_1": "Market timeline replay",
        "replay_future_item_2": "AI decision replay",
        "replay_future_item_3": "Strategy comparison replay",
    },
    "ja": {
        "research_title": "Research Lab",
        "research_subtitle": "短期の市場状態メモリ、レイテンシ傾向、collector 保存状況を確認します。",
        "research_tab_memory": "市場状態メモリ",
        "research_tab_latency": "レイテンシ",
        "research_tab_storage": "保存状況",
        "research_memory_title": "市場状態メモリ履歴",
        "research_memory_empty": "永続化された市場状態メモリはまだありません。",
        "research_memory_spread": "スプレッド",
        "research_memory_imbalance": "板バランス",
        "research_memory_delta": "約定デルタ",
        "research_memory_wall_ratio": "壁比率",
        "research_latency_title": "レイテンシ傾向",
        "research_latency_empty": "レイテンシ行がありません。",
        "research_latency_avg": "平均レイテンシ(ms)",
        "research_latency_max": "最大レイテンシ(ms)",
        "research_latency_count": "レイテンシ件数",
        "research_storage_title": "Collector 保存状況",
        "research_storage_orderbook": "Orderbook",
        "research_storage_trades": "Trades",
        "research_storage_file_count": "ファイル数",
        "research_storage_latest_file": "最新ファイル",
        "research_storage_latest_size": "最新サイズ(MB)",
        "research_tactic_stance_summary_title": "戦術スタンス要約",

        "replay_title": "Replay Lab",
        "replay_subtitle": "直近の audit イベントと市場状態メモリを見返し、将来の replay 機能の土台を確認します。",
        "replay_tab_events": "イベント",
        "replay_tab_memory": "市場状態メモリ",
        "replay_tab_future": "将来の Replay",
        "replay_events_title": "直近 audit イベント",
        "replay_events_empty": "再確認できるイベントがありません。",
        "replay_events_count": "イベント数",
        "replay_events_avg_latency": "平均レイテンシ(ms)",
        "replay_events_max_latency": "最大レイテンシ(ms)",
        "replay_memory_title": "永続化された市場状態メモリ",
        "replay_memory_empty": "永続化された市場状態メモリはありません。",
        "replay_future_title": "Replay ロードマップ",
        "replay_future_desc": "この空間は将来、完全な replay ワークフローへ進化します。",
        "replay_future_item_1": "市場タイムライン replay",
        "replay_future_item_2": "AI判断 replay",
        "replay_future_item_3": "戦略比較 replay",
    },
}