# path: ./btcts_next/src/btcts/apps/operator_ui/texts/warroom.py
# desc: War Room related text keys for market panels, alerts, strategy, and AI operator views.

WARROOM_TEXTS = {
    "en": {
        "warroom_title": "War Room",
        "warroom_caption": "This page uses replay / research / experiment artifacts for assisted market analysis and AI interpretation.",
        "market_regime_title": "Market Regime",
        "market_monitor_title": "Market Monitor",
        "liquidity_pressure_title": "Liquidity Pressure",
        "trade_flow_title": "Trade Flow",
        "graph_overlay_contract_title": "Graph Overlay Contract",
        "trade_flow_recent_count_caption": "{label}: {count}",
        "trade_flow_source_ts_caption": "source={source} / ts={ts}",
        "trade_flow_microstructure_caption": "microstructure: {names}",
        "warroom_generic_source_caption": "source={source}",
        "ai_signal_title": "AI Signal",
        "strategy_state_title": "Strategy State",
        "risk_monitor_title": "Risk Monitor",
        "warroom_timeline_title": "Situation Timeline",
        "warroom_alert_title": "War Room Alerts",
        "ai_operator_title": "AI Operator",
        "decision_log_title": "AI Operator Decision Log",
        "watch_list_title": "Watch List",
        "strategy_state_artifact_missing": "Research artifact is not available yet.",
        "strategy_state_research_summary": "Research Suggestion",
        "warroom_alert_runtime_caption": "Alerts are generated from live_canonical / research_experiment / recent audit latency.",
        "ui_slot_diagnostics_warroom_caption": "warroom page slot registry / refresh_mode and priority draft",
        "ui_slot_registry_empty_warroom": "warroom slot registry is empty",
        "warroom_graph_overlay_diagnostics_title": "War Room Graph Overlay Diagnostics",
        "warroom_overlay_enabled_widgets_caption": "overlay-enabled widgets: {count} / {total}",
        "warroom_partial_update_enabled_widgets_caption": "partial-update-enabled widgets: {count} / {total}",
        "warroom_overlay_diagnostics_targets_caption": "overlay diagnostics targets: {count}",
        "warroom_chart_sensitive_widgets_caption": "chart-sensitive widgets: {count}",
        "warroom_refresh_modes_caption": "refresh modes: {counts}",
        "ai_operator_live_local_prefix": "local AI mode active: generating a local summary based on live_canonical",
        "risk_monitor_level": "Risk Level",
        "risk_monitor_score": "Risk Score",

        "warroom_alert_severity_critical": "CRITICAL",
        "warroom_alert_severity_warning": "WARNING",
        "warroom_alert_severity_info": "INFO",
        "warroom_alert_spread_state_changed": "Spread state changed to {state}.",
        "warroom_alert_pressure_changed": "Orderbook pressure changed to {state}.",
        "warroom_alert_ai_decision_changed": "AI decision changed to {state}.",
        "warroom_alert_risk_spike": "Risk level escalated to HIGH.",
        "warroom_alert_strategy_snapshot": "Current strategy snapshot: {strategy}.",
        "warroom_alert_value_wide": "WIDE",
        "warroom_alert_value_tight": "TIGHT",
        "warroom_alert_value_normal": "NORMAL",
        "warroom_alert_value_buy_pressure": "BUY PRESSURE",
        "warroom_alert_value_sell_pressure": "SELL PRESSURE",
        "warroom_alert_value_long_bias": "LONG BIAS",
        "warroom_alert_value_short_bias": "SHORT BIAS",
        "warroom_alert_value_wait": "WAIT",

        "warroom_timeline_missing_data": "Timeline data is not available.",
        "warroom_timeline_empty": "No timeline changes yet.",
        "warroom_timeline_caption": "Latest detected changes from replay / research assisted War Room sources.",
        "warroom_timeline_regime": "Regime",
        "warroom_timeline_spread": "Spread State",
        "warroom_timeline_pressure": "Pressure",
        "warroom_timeline_decision": "AI Decision",

        "warroom_value_range": "RANGE",
        "warroom_value_trend": "TREND",
        "warroom_value_liquidity_vacuum": "LIQUIDITY VACUUM",
        "warroom_value_absorption": "ABSORPTION ZONE",
        "warroom_value_buy": "BUY",
        "warroom_value_sell": "SELL",
        "warroom_value_neutral": "NEUTRAL",
        "warroom_value_long_bias": "LONG BIAS",
        "warroom_value_short_bias": "SHORT BIAS",
        "warroom_value_wait": "WAIT",

        "risk_monitor_missing_data": "Risk data is not available.",
        "risk_monitor_latency": "Latency Risk",
        "risk_monitor_spread": "Spread Risk",
        "risk_value_low": "LOW",
        "risk_value_medium": "MEDIUM",
        "risk_value_high": "HIGH",

        "market_regime_missing_data": "Market regime data is not available.",
        "market_regime_regime": "Regime",
        "market_regime_spread_state": "Spread State",
        "market_regime_pressure": "Pressure",
        "market_regime_flow_agreement": "Flow Agreement",
        "market_regime_value_normal": "NORMAL",
        "market_regime_value_wide": "WIDE",
        "market_regime_value_tight": "TIGHT",
        "market_regime_value_buy": "BUY",
        "market_regime_value_sell": "SELL",
        "market_regime_value_neutral": "NEUTRAL",
        "market_regime_value_range": "RANGE",
        "market_regime_value_trend": "TREND",
        "market_regime_value_liquidity_vacuum": "LIQUIDITY VACUUM",
        "market_regime_value_volatility_expansion": "VOLATILITY EXPANSION",
        "market_regime_value_mixed": "MIXED",
        "market_regime_value_buy_confirm": "BUY CONFIRM",
        "market_regime_value_sell_confirm": "SELL CONFIRM",

        "market_monitor_not_found": "Market monitor data is not available.",
        "market_monitor_spread": "Spread",
        "market_monitor_bid_volume": "Bid Volume (Top10)",
        "market_monitor_ask_volume": "Ask Volume (Top10)",
        "market_monitor_imbalance": "Orderbook Imbalance",
        "market_monitor_trust": "Trust",
        "market_monitor_continuity": "Continuity",
        "market_monitor_interpretation": "Interpretation",
        "market_monitor_best_bid_ask_ts_line": "best_bid={best_bid} / best_ask={best_ask} / ts={ts}",
        "market_monitor_source_line": "board_source={board_source} / state_source={state_source} / preferred_state_freshness={preferred_state_freshness}",
        "market_monitor_interpretation_line": "continuity_state={continuity_state} / interpretation_bucket={interpretation_bucket} / interpretation_reason={interpretation_reason}",
        "market_monitor_market_state_line": "market_state_freshness={market_state_freshness} / market_state_age_sec={market_state_age_sec}",
        "market_monitor_stale_posture_caption": "state posture is stale; live board remains primary while last trusted interpretation is retained",
        "market_monitor_source_unknown": "unknown",
        "market_monitor_source_live_canonical": "live canonical",
        "market_monitor_source_market_state_live": "market state live",
        "market_monitor_source_replay_board_fallback": "replay board fallback",
        "market_monitor_source_market_state_preferred": "market state preferred",

        "liquidity_pressure_not_found": "Liquidity pressure data is not available.",
        "liquidity_pressure_top_bid_wall": "Top Bid Wall",
        "liquidity_pressure_top_ask_wall": "Top Ask Wall",
        "liquidity_pressure_wall_ratio": "Wall Ratio",
        "liquidity_pressure_wall_bias": "Wall Bias",
        "liquidity_pressure_value_neutral": "NEUTRAL",
        "liquidity_pressure_value_buy": "BUY",
        "liquidity_pressure_value_sell": "SELL",
        "badge_liquidity_bias": "Liquidity Bias",

        "trade_flow_not_found": "Trade flow data is not available.",
        "trade_flow_buy_volume": "Buy Volume",
        "trade_flow_sell_volume": "Sell Volume",
        "trade_flow_delta": "Delta",
        "trade_flow_recent_count": "Recent trades",

        "ai_signal_missing_data": "AI signal data is not available.",
        "ai_signal_market_regime": "Market Regime",
        "ai_signal_orderbook_bias": "Orderbook Bias",
        "ai_signal_trade_delta": "Trade Delta",
        "ai_signal_decision": "AI Decision",
        "ai_signal_value_range": "RANGE",
        "ai_signal_value_trend": "TREND",
        "ai_signal_value_wait": "WAIT",
        "ai_signal_value_long_bias": "LONG BIAS",
        "ai_signal_value_short_bias": "SHORT BIAS",
        "badge_ai_decision": "AI Decision",

        "strategy_state_mode": "Strategy Mode",
        "strategy_state_risk": "Risk State",
        "strategy_state_archetype": "Archetype",
        "strategy_state_confidence": "Confidence",
        "strategy_state_value_neutral": "NEUTRAL",
        "strategy_state_value_medium": "MEDIUM",
        "strategy_state_value_low": "LOW",
        "strategy_state_value_high": "HIGH",
        "strategy_state_value_long_trend": "LONG TREND",
        "strategy_state_value_short_trend": "SHORT TREND",
        "strategy_state_value_range_scalp": "RANGE SCALP",
        "strategy_state_value_volatility_watch": "VOLATILITY WATCH",
        "badge_strategy_mode": "Strategy Mode",
        "badge_risk_state": "Risk State",
        "strategy_state_artifact_title": "Latest Research Strategy Artifact",

        "ai_summary_title": "AI Market Summary",
        "ai_summary_missing_data": "AI market summary data is not available.",
        "ai_summary_headline": "Headline",
        "ai_summary_bullets": "Key Points",
        "ai_summary_outlook": "Outlook",
        "ai_summary_value_buy_bias": "Orderbook bias leans BUY.",
        "ai_summary_value_sell_bias": "Orderbook bias leans SELL.",
        "ai_summary_value_neutral_bias": "Orderbook bias is NEUTRAL.",
        "ai_summary_value_wide_spread": "Spread is wide.",
        "ai_summary_value_tight_spread": "Spread is tight.",
        "ai_summary_value_buy_flow": "Trade flow is buy-dominant.",
        "ai_summary_value_sell_flow": "Trade flow is sell-dominant.",
        "ai_summary_value_long_watch": "LONG WATCH",
        "ai_summary_value_short_watch": "SHORT WATCH",
        "ai_summary_value_wait": "WAIT",

        "ai_conversation_title": "AI Conversation",
        "ai_conversation_prompt": "Suggested Prompt",
        "ai_conversation_q1": "Explain the current market state.",
        "ai_conversation_q2": "What action should the operator take now?",
        "ai_conversation_q3": "What is the current risk posture?",
        "ai_conversation_q4": "How should we interpret board and trade flow together?",
        "ai_conversation_intent": "Intent",
        "ai_conversation_intent_explain": "Explain",
        "ai_conversation_intent_decide": "Decision Support",
        "ai_conversation_intent_risk": "Risk Review",
        "ai_conversation_intent_wall": "Wall Focus",
        "ai_conversation_style": "Style",
        "ai_conversation_style_concise": "Concise",
        "ai_conversation_style_normal": "Normal",
        "ai_conversation_style_deep": "Deep",
        "ai_conversation_custom_prompt": "Custom Prompt",
        "ai_conversation_note": "Operator Note",
        "ai_conversation_send": "Send",
        "ai_conversation_clear": "Clear",
        "ai_conversation_clear_done": "Conversation cleared.",
        "ai_conversation_result": "Result",
        "ai_conversation_state_spread": "Spread",
        "ai_conversation_state_imbalance": "Imbalance",
        "ai_conversation_state_delta": "Delta",
        "ai_conversation_state_wall_ratio": "Wall Ratio",
        "ai_conversation_effective_prompt": "Effective Prompt",
        "ai_runtime_mode": "AI Runtime Mode",
        "ai_runtime_source": "Runtime Source",
        "ai_conversation_placeholder": "Ask the AI using the current market state.",
        "ai_conversation_history": "Conversation History",
        "ai_conversation_user": "User",
        "ai_conversation_ai": "AI",
        "ai_conversation_empty_history": "No conversation history yet.",
        "ai_memory_title": "Market Memory",
        "ai_memory_spread_change": "Spread",
        "ai_memory_imbalance_change": "Imbalance",
        "ai_memory_delta_change": "Delta",
        "ai_memory_wall_ratio_change": "Wall Ratio",
        "ai_memory_empty": "No memory rows yet.",
        "ai_memory_persistent_hint": "Market memory is persisted from recent AI observations.",

        "warroom_header_title": "War Room Header",
        "warroom_header_missing_data": "War Room header data is not available.",
        "warroom_header_regime": "Regime",
        "warroom_header_spread_state": "Spread State",
        "warroom_header_pressure": "Pressure",
        "warroom_header_trade_flow": "Trade Flow",
        "warroom_header_ai_decision": "AI Decision",
        "warroom_header_risk": "Risk",
        "warroom_header_summary_caption": "best_strategy={best_strategy} / spread={spread} / imbalance={imbalance} / wall_ratio={wall_ratio}",
        "ai_reasoning_title": "AI Reasoning",
        "ai_reasoning_missing_data": "AI reasoning data is not available.",
        "ai_reasoning_metric_spread": "spread",
        "ai_reasoning_metric_imbalance": "imbalance",
        "ai_reasoning_metric_delta": "delta",
        "ai_reasoning_metric_wall": "wall",
        "ai_reasoning_metric_regime": "regime",
        "ai_reasoning_metric_strategy": "strategy",
        "ai_reasoning_headline": "Reasoning Headline",
        "ai_reasoning_points": "Reasoning Points",
        "ai_reasoning_summary": "Reasoning Summary",

        "warroom_value_unknown": "UNKNOWN",
        "warroom_value_low": "LOW",
        "warroom_value_medium": "MEDIUM",
        "warroom_value_high": "HIGH",

        "warroom_value_wide": "WIDE",
        "warroom_value_tight": "TIGHT",
        "warroom_value_normal": "NORMAL",
    },
    "ja": {
        "warroom_title": "War Room",
        "warroom_caption": "このページは replay / research / experiment artifact を基に、市場分析と AI 解釈を行う司令室です。",
        "market_regime_title": "市場レジーム",
        "market_monitor_title": "市場モニター",
        "liquidity_pressure_title": "流動性圧力",
        "trade_flow_title": "約定フロー",
        "graph_overlay_contract_title": "グラフ オーバーレイ契約",
        "trade_flow_recent_count_caption": "{label}: {count}",
        "trade_flow_source_ts_caption": "ソース={source} / ts={ts}",
        "trade_flow_microstructure_caption": "マイクロ構造: {names}",
        "warroom_generic_source_caption": "ソース={source}",
        "ai_signal_title": "AIシグナル",
        "strategy_state_title": "戦略状態",
        "risk_monitor_title": "リスクモニター",
        "warroom_timeline_title": "状況タイムライン",
        "warroom_alert_title": "War Room アラート",
        "ai_operator_title": "AIオペレーター",
        "decision_log_title": "AIオペレーター判断ログ",
        "watch_list_title": "ウォッチリスト",
        "strategy_state_artifact_missing": "研究アーティファクトがまだありません。",
        "strategy_state_research_summary": "研究推奨",
        "warroom_alert_runtime_caption": "アラートは live_canonical / research_experiment / 直近監査レイテンシを基に生成しています。",
        "ui_slot_diagnostics_warroom_caption": "warroom ページの slot registry / refresh_mode と priority の試験表示",
        "ui_slot_registry_empty_warroom": "warroom の slot registry は空です",
        "warroom_graph_overlay_diagnostics_title": "グラフ オーバーレイ診断",
        "warroom_overlay_enabled_widgets_caption": "オーバーレイ有効ウィジェット: {count} / {total}",
        "warroom_partial_update_enabled_widgets_caption": "部分更新有効ウィジェット: {count} / {total}",
        "warroom_overlay_diagnostics_targets_caption": "オーバーレイ診断対象: {count}",
        "warroom_chart_sensitive_widgets_caption": "チャート感応ウィジェット: {count}",
        "warroom_refresh_modes_caption": "更新モード集計: {counts}",
        "ai_operator_live_local_prefix": "local AI mode active: live_canonical を基にローカル要約を生成しています",
        "risk_monitor_level": "リスク水準",
        "risk_monitor_score": "リスクスコア",

        "warroom_alert_severity_critical": "重大",
        "warroom_alert_severity_warning": "警告",
        "warroom_alert_severity_info": "情報",
        "warroom_alert_spread_state_changed": "スプレッド状態が {state} に変化しました。",
        "warroom_alert_pressure_changed": "板圧力が {state} に変化しました。",
        "warroom_alert_ai_decision_changed": "AI判断が {state} に変化しました。",
        "warroom_alert_risk_spike": "リスク水準が HIGH に上昇しました。",
        "warroom_alert_strategy_snapshot": "現在の戦略スナップショット: {strategy}",
        "warroom_alert_value_wide": "広い",
        "warroom_alert_value_tight": "狭い",
        "warroom_alert_value_normal": "通常",
        "warroom_alert_value_buy_pressure": "買い圧力",
        "warroom_alert_value_sell_pressure": "売り圧力",
        "warroom_alert_value_long_bias": "ロング寄り",
        "warroom_alert_value_short_bias": "ショート寄り",
        "warroom_alert_value_wait": "待機",

        "warroom_timeline_missing_data": "タイムラインに必要なデータがありません。",
        "warroom_timeline_empty": "まだ変化ログがありません。",
        "warroom_timeline_caption": "replay / research assisted War Room ソースから検出した最新の変化です。",
        "warroom_timeline_regime": "レジーム",
        "warroom_timeline_spread": "スプレッド状態",
        "warroom_timeline_pressure": "圧力",
        "warroom_timeline_decision": "AI判断",

        "warroom_value_range": "レンジ",
        "warroom_value_trend": "トレンド",
        "warroom_value_liquidity_vacuum": "流動性真空",
        "warroom_value_absorption": "吸収帯",
        "warroom_value_buy": "買い",
        "warroom_value_sell": "売り",
        "warroom_value_neutral": "中立",
        "warroom_value_long_bias": "ロング寄り",
        "warroom_value_short_bias": "ショート寄り",
        "warroom_value_wait": "待機",

        "risk_monitor_missing_data": "リスクモニターに必要なデータがありません。",
        "risk_monitor_latency": "レイテンシリスク",
        "risk_monitor_spread": "スプレッドリスク",
        "risk_value_low": "低",
        "risk_value_medium": "中",
        "risk_value_high": "高",

        "market_regime_missing_data": "市場レジームに必要なデータがありません。",
        "market_regime_regime": "地合い",
        "market_regime_spread_state": "スプレッド状態",
        "market_regime_pressure": "圧力",
        "market_regime_flow_agreement": "フロー一致",
        "market_regime_value_normal": "通常",
        "market_regime_value_wide": "広い",
        "market_regime_value_tight": "狭い",
        "market_regime_value_buy": "買い",
        "market_regime_value_sell": "売り",
        "market_regime_value_neutral": "中立",
        "market_regime_value_range": "レンジ",
        "market_regime_value_trend": "トレンド",
        "market_regime_value_liquidity_vacuum": "流動性真空",
        "market_regime_value_volatility_expansion": "ボラ拡大",
        "market_regime_value_mixed": "混在",
        "market_regime_value_buy_confirm": "買い優勢確認",
        "market_regime_value_sell_confirm": "売り優勢確認",

        "market_monitor_not_found": "市場モニターに必要なデータがありません。",
        "market_monitor_spread": "スプレッド",
        "market_monitor_bid_volume": "買い板量(上位10)",
        "market_monitor_ask_volume": "売り板量(上位10)",
        "market_monitor_imbalance": "板バランス",
        "market_monitor_trust": "信頼度",
        "market_monitor_continuity": "連続性",
        "market_monitor_interpretation": "解釈状態",
        "market_monitor_best_bid_ask_ts_line": "best_bid={best_bid} / best_ask={best_ask} / ts={ts}",
        "market_monitor_source_line": "板ソース={board_source} / 状態ソース={state_source} / 優先状態鮮度={preferred_state_freshness}",
        "market_monitor_interpretation_line": "連続性={continuity_state} / 解釈バケット={interpretation_bucket} / 解釈理由={interpretation_reason}",
        "market_monitor_market_state_line": "market_state鮮度={market_state_freshness} / market_state経過秒={market_state_age_sec}",
        "market_monitor_stale_posture_caption": "状態姿勢が stale のため、ライブ板を主表示にしつつ、最後に trusted だった解釈を保持しています",
        "market_monitor_source_unknown": "不明",
        "market_monitor_source_live_canonical": "ライブ canonical",
        "market_monitor_source_market_state_live": "ライブ市場状態",
        "market_monitor_source_replay_board_fallback": "replay 板フォールバック",
        "market_monitor_source_market_state_preferred": "優先市場状態",

        "liquidity_pressure_not_found": "流動性圧力データがありません。",
        "liquidity_pressure_top_bid_wall": "最大買い壁",
        "liquidity_pressure_top_ask_wall": "最大売り壁",
        "liquidity_pressure_wall_ratio": "壁比率",
        "liquidity_pressure_wall_bias": "壁バイアス",
        "liquidity_pressure_value_neutral": "中立",
        "liquidity_pressure_value_buy": "買い",
        "liquidity_pressure_value_sell": "売り",
        "badge_liquidity_bias": "流動性バイアス",

        "trade_flow_not_found": "約定フローに必要なデータがありません。",
        "trade_flow_buy_volume": "買い量",
        "trade_flow_sell_volume": "売り量",
        "trade_flow_delta": "デルタ",
        "trade_flow_recent_count": "直近約定数",
        "ai_signal_missing_data": "AIシグナルに必要なデータがありません。",
        "ai_signal_market_regime": "市場レジーム",
        "ai_signal_orderbook_bias": "板バイアス",
        "ai_signal_trade_delta": "約定デルタ",
        "ai_signal_decision": "AI判断",
        "ai_signal_value_range": "レンジ",
        "ai_signal_value_trend": "トレンド",
        "ai_signal_value_wait": "待機",
        "ai_signal_value_long_bias": "ロング寄り",
        "ai_signal_value_short_bias": "ショート寄り",
        "badge_ai_decision": "AI判断",

        "strategy_state_mode": "戦略モード",
        "strategy_state_risk": "リスク状態",
        "strategy_state_archetype": "アーキタイプ",
        "strategy_state_confidence": "信頼度",
        "strategy_state_value_neutral": "中立",
        "strategy_state_value_medium": "中",
        "strategy_state_value_low": "低",
        "strategy_state_value_high": "高",
        "strategy_state_value_long_trend": "上昇トレンド",
        "strategy_state_value_short_trend": "下降トレンド",
        "strategy_state_value_range_scalp": "レンジスキャルプ",
        "strategy_state_value_volatility_watch": "ボラ監視",
        "badge_strategy_mode": "戦略モード",
        "badge_risk_state": "リスク状態",
        "strategy_state_artifact_title": "最新 Research 戦略 Artifact",

        "ai_summary_title": "AI市場サマリー",
        "ai_summary_missing_data": "AI市場サマリーに必要なデータがありません。",
        "ai_summary_headline": "見出し",
        "ai_summary_bullets": "要点",
        "ai_summary_outlook": "見通し",
        "ai_summary_value_buy_bias": "板バイアスは買い寄りです。",
        "ai_summary_value_sell_bias": "板バイアスは売り寄りです。",
        "ai_summary_value_neutral_bias": "板バイアスは中立です。",
        "ai_summary_value_wide_spread": "スプレッドは広いです。",
        "ai_summary_value_tight_spread": "スプレッドは狭いです。",
        "ai_summary_value_buy_flow": "約定フローは買い優勢です。",
        "ai_summary_value_sell_flow": "約定フローは売り優勢です。",
        "ai_summary_value_long_watch": "ロング監視",
        "ai_summary_value_short_watch": "ショート監視",
        "ai_summary_value_wait": "待機",

        "ai_conversation_title": "AI会話",
        "ai_conversation_prompt": "推奨プロンプト",
        "ai_conversation_q1": "現在の市場状態を説明してください。",
        "ai_conversation_q2": "いまオペレーターはどう動くべきですか？",
        "ai_conversation_q3": "現在のリスク姿勢はどう見ますか？",
        "ai_conversation_q4": "板と約定フローをどう合わせて解釈すべきですか？",
        "ai_conversation_intent": "意図",
        "ai_conversation_intent_explain": "説明",
        "ai_conversation_intent_decide": "判断補助",
        "ai_conversation_intent_risk": "リスク確認",
        "ai_conversation_intent_wall": "壁注目",
        "ai_conversation_style": "スタイル",
        "ai_conversation_style_concise": "簡潔",
        "ai_conversation_style_normal": "通常",
        "ai_conversation_style_deep": "深掘り",
        "ai_conversation_custom_prompt": "自由入力プロンプト",
        "ai_conversation_note": "オペレーターノート",
        "ai_conversation_send": "送信",
        "ai_conversation_clear": "クリア",
        "ai_conversation_clear_done": "会話履歴をクリアしました。",
        "ai_conversation_result": "結果",
        "ai_conversation_state_spread": "スプレッド",
        "ai_conversation_state_imbalance": "板バランス",
        "ai_conversation_state_delta": "デルタ",
        "ai_conversation_state_wall_ratio": "壁比率",
        "ai_conversation_effective_prompt": "実際に送るプロンプト",
        "ai_runtime_mode": "AI実行モード",
        "ai_runtime_source": "実行ソース",
        "ai_conversation_placeholder": "現在の市場状態を使って AI に質問してください。",
        "ai_conversation_history": "会話履歴",
        "ai_conversation_user": "ユーザー",
        "ai_conversation_ai": "AI",
        "ai_conversation_empty_history": "会話履歴はまだありません。",
        "ai_memory_title": "市場メモリ",
        "ai_memory_spread_change": "スプレッド",
        "ai_memory_imbalance_change": "板バランス",
        "ai_memory_delta_change": "デルタ",
        "ai_memory_wall_ratio_change": "壁比率",
        "ai_memory_empty": "メモリ行はまだありません。",
        "ai_memory_persistent_hint": "市場メモリは直近の AI 観測から永続化されます。",

        "warroom_header_title": "War Room ヘッダー",
        "warroom_header_missing_data": "War Room ヘッダーに必要なデータがありません。",
        "warroom_header_regime": "地合い",
        "warroom_header_spread_state": "スプレッド状態",
        "warroom_header_pressure": "圧力",
        "warroom_header_trade_flow": "約定フロー",
        "warroom_header_ai_decision": "AI判断",
        "warroom_header_risk": "リスク",
        "warroom_header_summary_caption": "best_strategy={best_strategy} / spread={spread} / imbalance={imbalance} / wall_ratio={wall_ratio}",
        "ai_reasoning_title": "AI推論",
        "ai_reasoning_missing_data": "AI推論に必要なデータがありません。",
        "ai_reasoning_metric_spread": "spread",
        "ai_reasoning_metric_imbalance": "imbalance",
        "ai_reasoning_metric_delta": "delta",
        "ai_reasoning_metric_wall": "wall",
        "ai_reasoning_metric_regime": "regime",
        "ai_reasoning_metric_strategy": "strategy",
        "ai_reasoning_headline": "推論ヘッドライン",
        "ai_reasoning_points": "推論ポイント",
        "ai_reasoning_summary": "推論まとめ",

        "warroom_value_unknown": "不明",
        "warroom_value_low": "低",
        "warroom_value_medium": "中",
        "warroom_value_high": "高",

        "warroom_value_wide": "広い",
        "warroom_value_tight": "狭い",
        "warroom_value_normal": "通常",
    },
}