# path: ./btcts_next/src/btcts/autotrade/execution/__init__.py
# desc: AutoTrade execution package. Contracts only; no broker client import.

from __future__ import annotations

from .command_ledger import (
    CommandLedgerRecord,
    append_command_ledger_record,
    build_command_ledger_record,
    default_command_ledger_path,
    read_command_ledger,
    validate_and_append_command,
)
from .command_request import CommandRequest, CommandType, CommandValidationResult, validate_command_request
from .command_status import CommandLedgerReadResult, CommandLedgerSummary, read_command_ledger_rows, summarize_command_ledger
from .dry_run import DryRunExecutionResult, evaluate_armed_dry_run_intent
from .intents import OrderIntent, OrderSide, OrderType, build_order_intent_from_decision
from .mode_change_request import (
    ModeChangeCommandRequestResult,
    build_mode_change_command_request_record,
    submit_mode_change_command_request,
)
from .mode_command_applier import (
    ModeChangeCommandApplyPreview,
    ModeChangeCommandApplyResult,
    ModeChangeCommandReadinessApplyPreview,
    ModeChangeCommandReadinessApplyResult,
    apply_latest_mode_change_command_once,
    apply_latest_mode_change_command_once_with_readiness_recheck,
    preview_latest_mode_change_command_apply,
    preview_latest_mode_change_command_apply_with_readiness_recheck,
)
from .mode_state import (
    DEFAULT_MODE_STATE,
    ModeStateReadResult,
    ModeStateRecord,
    ModeStateSummary,
    append_mode_state_record,
    build_mode_state_record_from_command,
    current_mode_state,
    default_mode_state_ledger_path,
    read_mode_state_records,
    summarize_mode_state,
)
from .order_state import PaperOrder, PaperOrderStatus, create_paper_order, paper_order_id_for_intent
from .order_preview import BitflyerFxOrderRequestPreview, OrderPreviewResult, build_bitflyer_fx_manual_order_preview, build_bitflyer_fx_order_request_preview
from .paper_intent import PaperOrderIntentBuildResult, build_fx_paper_order_intent_from_service_input, validate_execution_market_service_input_for_paper
from .paper_ledger import PaperOrderLedgerReadResult, PaperOrderLedgerRecord, PaperOrderLedgerSummary, PaperOrderLifecycleSummary, PaperOrderTransitionRecord, default_paper_order_ledger_path, record_paper_order, record_paper_order_transition, read_paper_order_ledger, read_paper_order_ledger_rows, read_paper_orders, summarize_paper_order_ledger, summarize_paper_order_lifecycle
from .paper_position import PaperFillEvent, PaperPositionSummary, summarize_paper_position_from_lifecycle
from .runtime_control import (
    DEFAULT_HEARTBEAT_MAX_AGE_SEC,
    DEFAULT_KILL_SWITCH_ACTION,
    RuntimeControlSnapshot,
    RuntimeHeartbeatState,
    RuntimeIncidentRecord,
    RuntimeKillSwitchState,
    build_runtime_control_snapshot,
    build_runtime_heartbeat_state,
    build_runtime_incident_record,
    build_runtime_kill_switch_state,
    read_runtime_control_snapshot,
    runtime_control_state_path,
    write_runtime_control_snapshot,
)
from .reconciliation import FxReconciliationResult, reconcile_fx_private_state_with_paper, reconcile_fx_private_state_with_paper_ledger
from .safety_harness import SrFxExecutionSafetyHarnessResult, evaluate_sr_fx_execution_safety_harness
from .live_readiness_contract import FxLiveReadinessContractResult, evaluate_fx_live_readiness_contract

__all__ = [
    "write_runtime_control_snapshot",
    "runtime_control_state_path",
    "read_runtime_control_snapshot",
    "build_runtime_kill_switch_state",
    "build_runtime_incident_record",
    "build_runtime_heartbeat_state",
    "build_runtime_control_snapshot",
    "RuntimeKillSwitchState",
    "RuntimeIncidentRecord",
    "RuntimeHeartbeatState",
    "RuntimeControlSnapshot",
    "DEFAULT_KILL_SWITCH_ACTION",
    "DEFAULT_HEARTBEAT_MAX_AGE_SEC",
    "BitflyerFxOrderRequestPreview",
    "OrderPreviewResult",
    "build_bitflyer_fx_manual_order_preview",
    "build_bitflyer_fx_order_request_preview",
    "FxReconciliationResult",
    "reconcile_fx_private_state_with_paper",
    "reconcile_fx_private_state_with_paper_ledger",
    "FxLiveReadinessContractResult",
    "SrFxExecutionSafetyHarnessResult",
    "evaluate_fx_live_readiness_contract",
    "evaluate_sr_fx_execution_safety_harness",
    "CommandLedgerReadResult",
    "CommandLedgerRecord",
    "CommandLedgerSummary",
    "CommandRequest",
    "CommandType",
    "CommandValidationResult",
    "DryRunExecutionResult",
    "ModeChangeCommandApplyPreview",
    "ModeChangeCommandApplyResult",
    "ModeChangeCommandReadinessApplyPreview",
    "ModeChangeCommandReadinessApplyResult",
    "ModeChangeCommandRequestResult",
    "ModeStateReadResult",
    "ModeStateRecord",
    "ModeStateSummary",
    "OrderIntent",
    "OrderSide",
    "OrderType",
    "PaperOrder",
    "PaperOrderStatus",
    "PaperOrderIntentBuildResult",
    "PaperOrderLedgerRecord",
    "PaperOrderLedgerReadResult",
    "PaperOrderLedgerSummary",
    "PaperOrderLifecycleSummary",
    "PaperOrderTransitionRecord",
    "PaperFillEvent",
    "PaperPositionSummary",
    "DEFAULT_MODE_STATE",
    "append_command_ledger_record",
    "apply_latest_mode_change_command_once",
    "apply_latest_mode_change_command_once_with_readiness_recheck",
    "preview_latest_mode_change_command_apply",
    "preview_latest_mode_change_command_apply_with_readiness_recheck",
    "append_mode_state_record",
    "build_command_ledger_record",
    "build_mode_change_command_request_record",
    "build_mode_state_record_from_command",
    "build_order_intent_from_decision",
    "build_fx_paper_order_intent_from_service_input",
    "default_paper_order_ledger_path",
    "create_paper_order",
    "current_mode_state",
    "default_command_ledger_path",
    "default_mode_state_ledger_path",
    "evaluate_armed_dry_run_intent",
    "paper_order_id_for_intent",
    "read_command_ledger",
    "record_paper_order",
    "record_paper_order_transition",
    "read_paper_order_ledger",
    "read_paper_order_ledger_rows",
    "read_paper_orders",
    "summarize_paper_order_ledger",
    "summarize_paper_order_lifecycle",
    "summarize_paper_position_from_lifecycle",
    "read_command_ledger_rows",
    "read_mode_state_records",
    "submit_mode_change_command_request",
    "summarize_command_ledger",
    "summarize_mode_state",
    "validate_and_append_command",
    "validate_command_request",
    "validate_execution_market_service_input_for_paper",
]
