# path: ./btcts_next/src/btcts/apps/operator_ui/components/ai_operator_display_sources.py
# desc: AI Operator の display source widget 読込を分離した境界。

from __future__ import annotations

from btcts.apps.operator_ui.components.market_state_bridge import (
    load_execution_market_summary_widget_model,
    load_execution_market_prediction_summary_widget_model,
    load_execution_market_prediction_tactic_proposal_payload,
    load_prediction_review_hint_summary_payload,
)
from btcts.apps.operator_ui.components.review_hint_presenter import (
    review_hint_display_sections,
)

AI_OPERATOR_DISPLAY_SOURCE_CATALOG = (
    {
        "source_key": "decision_policy_gate_read_only_visibility_registry_chain_completion_closeout_review_chain_closeout_final_status_index_registry_visibility_chain_completion_final_status_index",
        "source_type": "decision_policy_gate_read_only_visibility_registry_chain_completion_closeout_review_chain_closeout_final_status_index_registry_visibility_chain_completion_final_status_index_packet",
        "consumer_scope": ("ai_tab", "prediction_tab", "health_tab", "future_widget"),
        "status_index_module": "btcts.apps.operator_ui.hub.decision_policy_gate_chain_completion_final_status_index",
        "status_index_builder": "build_decision_policy_gate_visibility_registry_chain_completion_closeout_review_chain_closeout_final_status_index_registry_visibility_chain_completion_final_status_index_packet",
        "source_dependencies": (
            "decision_policy_gate_visibility_registry_chain_completion_closeout_review_chain_closeout_final_status_index_registry_visibility_chain_completion",
            "decision_policy_gate_visibility_registry_chain_completion_closeout_review_chain_closeout_final_status_index_registry_visibility_chain_completion_registry_visibility",
        ),
        "read_only_contract": True,
        "non_executing": True,
        "widget_reusable": True,
        "layout_decision_free": True,
        "data_model_only": True,
        "status_index_only": True,
        "final_status_index_only": True,
        "chain_completion_final_status_index_only": True,
        "registry_visibility_chain_completion_final_status_index_only": True,
        "chain_closeout_final_status_index_registry_visibility_chain_completion_final_status_index_only": True,
        "closeout_review_chain_closeout_final_status_index_registry_visibility_chain_completion_final_status_index_only": True,
        "not_runtime_payload_loading": True,
        "not_runtime_wiring": True,
        "not_ui_rendering": True,
        "no_command_buttons": True,
        "command_buttons_allowed": False,
        "forms_or_toggles_allowed": False,
        "runtime_wiring_allowed": False,
        "ui_rendering_implementation_allowed": False,
        "decision_append_allowed": False,
        "decision_ledger_integration_allowed": False,
        "live_shadow_behavior_change_allowed": False,
        "persist_true_allowed": False,
        "would_append_shadow_decision": False,
        "would_apply_mode": False,
        "would_execute_prearmed_grant": False,
        "would_write_runtime_artifact": False,
        "would_write_preview_status_artifact": False,
        "would_send_to_broker": False,
    },
    {
        "source_key": "decision_policy_gate_visibility_registry_chain_completion_closeout_review_chain_closeout_final_status_index_registry_visibility_chain_completion",
        "source_type": "decision_policy_gate_read_only_visibility_registry_chain_completion_closeout_review_chain_closeout_final_status_index_registry_visibility_chain_completion_packet",
        "consumer_scope": ("ai_tab", "prediction_tab", "health_tab", "future_widget"),
        "chain_completion_module": "btcts.apps.operator_ui.hub.decision_policy_gate_visibility_registry_chain_completion_closeout_review_chain_closeout_final_status_index_registry_visibility_chain_completion",
        "chain_completion_builder": "build_decision_policy_gate_visibility_registry_chain_completion_closeout_review_chain_closeout_final_status_index_registry_visibility_chain_completion_packet",
        "source_dependencies": (
            "decision_policy_gate_visibility_registry_chain_completion_closeout_review_chain_closeout_final_status_index",
            "decision_policy_gate_visibility_registry_chain_completion_closeout_review_chain_closeout_final_status_index_registry_visibility",
        ),
        "read_only_contract": True,
        "non_executing": True,
        "widget_reusable": True,
        "layout_decision_free": True,
        "data_model_only": True,
        "chain_completion_only": True,
        "registry_visibility_chain_completion_only": True,
        "chain_closeout_final_status_index_registry_visibility_chain_completion_only": True,
        "closeout_review_chain_closeout_final_status_index_registry_visibility_chain_completion_only": True,
        "not_runtime_payload_loading": True,
        "not_runtime_wiring": True,
        "not_ui_rendering": True,
        "no_command_buttons": True,
        "command_buttons_allowed": False,
        "forms_or_toggles_allowed": False,
        "runtime_wiring_allowed": False,
        "ui_rendering_implementation_allowed": False,
        "decision_append_allowed": False,
        "decision_ledger_integration_allowed": False,
        "live_shadow_behavior_change_allowed": False,
        "persist_true_allowed": False,
        "would_append_shadow_decision": False,
        "would_apply_mode": False,
        "would_execute_prearmed_grant": False,
        "would_write_runtime_artifact": False,
        "would_write_preview_status_artifact": False,
        "would_send_to_broker": False,
    },
    {
        "source_key": "decision_policy_gate_visibility_registry_chain_completion_closeout_review_chain_closeout_final_status_index",
        "source_type": "decision_policy_gate_read_only_visibility_registry_chain_completion_closeout_review_chain_closeout_final_status_index_packet",
        "consumer_scope": ("ai_tab", "prediction_tab", "health_tab", "future_widget"),
        "status_index_module": "btcts.apps.operator_ui.hub.decision_policy_gate_visibility_registry_chain_completion_closeout_review_chain_closeout_final_status_index",
        "status_index_builder": "build_decision_policy_gate_visibility_registry_chain_completion_closeout_review_chain_closeout_final_status_index_packet",
        "source_dependencies": (
            "decision_policy_gate_visibility_registry_chain_completion_closeout_review_chain_closeout_summary",
            "decision_policy_gate_visibility_registry_chain_completion_closeout_review_chain_closeout_summary_registry_visibility",
        ),
        "read_only_contract": True,
        "non_executing": True,
        "widget_reusable": True,
        "layout_decision_free": True,
        "data_model_only": True,
        "status_index_only": True,
        "final_status_index_only": True,
        "chain_closeout_final_status_index_only": True,
        "closeout_review_chain_closeout_final_status_index_only": True,
        "registry_visibility_chain_completion_closeout_review_chain_closeout_final_status_index_only": True,
        "not_runtime_payload_loading": True,
        "not_runtime_wiring": True,
        "not_ui_rendering": True,
        "no_command_buttons": True,
        "command_buttons_allowed": False,
        "forms_or_toggles_allowed": False,
        "runtime_wiring_allowed": False,
        "ui_rendering_implementation_allowed": False,
        "decision_append_allowed": False,
        "decision_ledger_integration_allowed": False,
        "live_shadow_behavior_change_allowed": False,
        "persist_true_allowed": False,
        "would_append_shadow_decision": False,
        "would_apply_mode": False,
        "would_execute_prearmed_grant": False,
        "would_write_runtime_artifact": False,
        "would_write_preview_status_artifact": False,
        "would_send_to_broker": False,
    },
    {
        "source_key": "decision_policy_gate_visibility_registry_chain_completion_closeout_review_chain_closeout_summary",
        "source_type": "decision_policy_gate_read_only_visibility_registry_chain_completion_closeout_review_chain_closeout_summary_packet",
        "consumer_scope": ("ai_tab", "prediction_tab", "health_tab", "future_widget"),
        "chain_closeout_summary_module": "btcts.apps.operator_ui.hub.decision_policy_gate_visibility_registry_chain_completion_closeout_review_chain_closeout_summary",
        "chain_closeout_summary_builder": "build_decision_policy_gate_visibility_registry_chain_completion_closeout_review_chain_closeout_summary_packet",
        "source_dependencies": (
            "decision_policy_gate_visibility_registry_chain_completion_closeout_review",
            "decision_policy_gate_visibility_registry_chain_completion_closeout_review_registry_visibility",
            "decision_policy_gate_visibility_registry_chain_completion_closeout_review_final_status_index",
            "decision_policy_gate_visibility_registry_chain_completion_closeout_review_final_status_index_registry_visibility",
        ),
        "read_only_contract": True,
        "non_executing": True,
        "widget_reusable": True,
        "layout_decision_free": True,
        "data_model_only": True,
        "chain_closeout_summary_only": True,
        "closeout_review_chain_closeout_summary_only": True,
        "registry_visibility_chain_completion_closeout_review_chain_closeout_summary_only": True,
        "not_runtime_payload_loading": True,
        "not_runtime_wiring": True,
        "not_ui_rendering": True,
        "no_command_buttons": True,
        "command_buttons_allowed": False,
        "forms_or_toggles_allowed": False,
        "runtime_wiring_allowed": False,
        "ui_rendering_implementation_allowed": False,
        "decision_append_allowed": False,
        "decision_ledger_integration_allowed": False,
        "live_shadow_behavior_change_allowed": False,
        "persist_true_allowed": False,
        "would_append_shadow_decision": False,
        "would_apply_mode": False,
        "would_execute_prearmed_grant": False,
        "would_write_runtime_artifact": False,
        "would_write_preview_status_artifact": False,
        "would_send_to_broker": False,
    },
    {
        "source_key": "decision_policy_gate_visibility_registry_chain_completion_closeout_review_final_status_index",
        "source_type": "decision_policy_gate_read_only_visibility_registry_chain_completion_closeout_review_final_status_index_packet",
        "consumer_scope": ("ai_tab", "prediction_tab", "health_tab", "future_widget"),
        "status_index_module": "btcts.apps.operator_ui.hub.decision_policy_gate_visibility_registry_chain_completion_closeout_review_final_status_index",
        "status_index_builder": "build_decision_policy_gate_visibility_registry_chain_completion_closeout_review_final_status_index_packet",
        "source_dependencies": (
            "decision_policy_gate_visibility_registry_chain_completion_closeout_review",
            "decision_policy_gate_visibility_registry_chain_completion_closeout_review_registry_visibility",
        ),
        "read_only_contract": True,
        "non_executing": True,
        "widget_reusable": True,
        "layout_decision_free": True,
        "data_model_only": True,
        "status_index_only": True,
        "final_status_index_only": True,
        "closeout_review_final_status_index_only": True,
        "registry_visibility_chain_completion_closeout_review_final_status_index_only": True,
        "not_runtime_payload_loading": True,
        "not_runtime_wiring": True,
        "not_ui_rendering": True,
        "no_command_buttons": True,
        "command_buttons_allowed": False,
        "forms_or_toggles_allowed": False,
        "runtime_wiring_allowed": False,
        "ui_rendering_implementation_allowed": False,
        "decision_append_allowed": False,
        "decision_ledger_integration_allowed": False,
        "live_shadow_behavior_change_allowed": False,
        "persist_true_allowed": False,
        "would_append_shadow_decision": False,
        "would_apply_mode": False,
        "would_execute_prearmed_grant": False,
        "would_write_runtime_artifact": False,
        "would_write_preview_status_artifact": False,
        "would_send_to_broker": False,
    },
    {
        "source_key": "decision_policy_gate_visibility_registry_chain_completion_closeout_review",
        "source_type": "decision_policy_gate_read_only_visibility_registry_chain_completion_closeout_review_packet",
        "consumer_scope": ("ai_tab", "prediction_tab", "health_tab", "future_widget"),
        "closeout_review_module": "btcts.apps.operator_ui.hub.decision_policy_gate_visibility_registry_chain_completion_closeout_review",
        "closeout_review_builder": "build_decision_policy_gate_visibility_registry_chain_completion_closeout_review_packet",
        "source_dependencies": (
            "autotrade_decision_ledger_policy_gate_display",
            "decision_policy_gate_static_section_model",
            "decision_policy_gate_dashboard_status_index",
            "decision_policy_gate_visibility_chain_summary",
            "decision_policy_gate_visibility_completion_checkpoint",
            "decision_policy_gate_visibility_completion_status_index",
            "decision_policy_gate_visibility_completion_status_index_registry_visibility_chain_completion",
            "decision_policy_gate_visibility_completion_status_index_registry_visibility_chain_completion_final_status_index",
            "decision_policy_gate_visibility_registry_chain_completion_final_status_index_registry_visibility",
        ),
        "read_only_contract": True,
        "non_executing": True,
        "widget_reusable": True,
        "layout_decision_free": True,
        "data_model_only": True,
        "closeout_review_only": True,
        "continuation_review_only": True,
        "catalog_metadata_only": True,
        "registry_visibility_review_only": True,
        "not_runtime_payload_loading": True,
        "not_runtime_wiring": True,
        "not_ui_rendering": True,
        "no_command_buttons": True,
        "command_buttons_allowed": False,
        "forms_or_toggles_allowed": False,
        "runtime_wiring_allowed": False,
        "ui_rendering_implementation_allowed": False,
        "decision_append_allowed": False,
        "decision_ledger_integration_allowed": False,
        "live_shadow_behavior_change_allowed": False,
        "persist_true_allowed": False,
        "would_append_shadow_decision": False,
        "would_apply_mode": False,
        "would_execute_prearmed_grant": False,
        "would_write_runtime_artifact": False,
        "would_write_preview_status_artifact": False,
        "would_send_to_broker": False,
    },
    {
        "source_key": "decision_policy_gate_visibility_completion_status_index_registry_visibility_chain_completion_final_status_index",
        "source_type": "decision_policy_gate_read_only_visibility_completion_status_index_registry_visibility_chain_completion_final_status_index_packet",
        "consumer_scope": ("ai_tab", "prediction_tab", "health_tab", "future_widget"),
        "status_index_module": "btcts.apps.operator_ui.hub.decision_policy_gate_visibility_registry_chain_completion_final_status_index",
        "status_index_builder": "build_decision_policy_gate_visibility_registry_chain_completion_final_status_index_packet",
        "source_dependencies": (
            "autotrade_decision_ledger_policy_gate_display",
            "decision_policy_gate_static_section_model",
            "decision_policy_gate_dashboard_status_index",
            "decision_policy_gate_visibility_chain_summary",
            "decision_policy_gate_visibility_completion_checkpoint",
            "decision_policy_gate_visibility_completion_status_index",
            "decision_policy_gate_visibility_completion_status_index_registry_visibility_chain_completion",
            "decision_policy_gate_visibility_registry_chain_completion_registry_visibility",
        ),
        "read_only_contract": True,
        "non_executing": True,
        "widget_reusable": True,
        "layout_decision_free": True,
        "data_model_only": True,
        "status_index_only": True,
        "final_status_index_only": True,
        "registry_visibility_chain_completion_final_status_index_only": True,
        "not_runtime_payload_loading": True,
        "not_runtime_wiring": True,
        "not_ui_rendering": True,
        "no_command_buttons": True,
        "command_buttons_allowed": False,
        "forms_or_toggles_allowed": False,
        "runtime_wiring_allowed": False,
        "ui_rendering_implementation_allowed": False,
        "decision_append_allowed": False,
        "decision_ledger_integration_allowed": False,
        "live_shadow_behavior_change_allowed": False,
        "persist_true_allowed": False,
        "would_append_shadow_decision": False,
        "would_apply_mode": False,
        "would_execute_prearmed_grant": False,
        "would_write_runtime_artifact": False,
        "would_write_preview_status_artifact": False,
        "would_send_to_broker": False,
    },
    {
        "source_key": "decision_policy_gate_visibility_completion_status_index_registry_visibility_chain_completion",
        "source_type": "decision_policy_gate_read_only_visibility_completion_status_index_registry_visibility_chain_completion_packet",
        "consumer_scope": ("ai_tab", "prediction_tab", "health_tab", "future_widget"),
        "chain_completion_module": "btcts.apps.operator_ui.hub.decision_policy_gate_visibility_completion_status_index_registry_visibility_chain_completion",
        "chain_completion_builder": "build_decision_policy_gate_visibility_completion_status_index_registry_visibility_chain_completion_packet",
        "source_dependencies": (
            "autotrade_decision_ledger_policy_gate_display",
            "decision_policy_gate_static_section_model",
            "decision_policy_gate_dashboard_status_index",
            "decision_policy_gate_visibility_chain_summary",
            "decision_policy_gate_visibility_completion_checkpoint",
            "decision_policy_gate_visibility_completion_status_index",
            "decision_policy_gate_visibility_completion_status_index_registry_visibility",
        ),
        "read_only_contract": True,
        "non_executing": True,
        "widget_reusable": True,
        "layout_decision_free": True,
        "data_model_only": True,
        "chain_completion_only": True,
        "registry_visibility_chain_completion_only": True,
        "visibility_completion_status_index_registry_visibility_chain_completion_only": True,
        "not_runtime_payload_loading": True,
        "not_runtime_wiring": True,
        "not_ui_rendering": True,
        "no_command_buttons": True,
        "command_buttons_allowed": False,
        "forms_or_toggles_allowed": False,
        "runtime_wiring_allowed": False,
        "ui_rendering_implementation_allowed": False,
        "decision_append_allowed": False,
        "decision_ledger_integration_allowed": False,
        "live_shadow_behavior_change_allowed": False,
        "persist_true_allowed": False,
        "would_append_shadow_decision": False,
        "would_apply_mode": False,
        "would_execute_prearmed_grant": False,
        "would_write_runtime_artifact": False,
        "would_write_preview_status_artifact": False,
        "would_send_to_broker": False,
    },
    {
        "source_key": "decision_policy_gate_visibility_completion_status_index",
        "source_type": "decision_policy_gate_read_only_visibility_completion_status_index_packet",
        "consumer_scope": ("ai_tab", "prediction_tab", "health_tab", "future_widget"),
        "status_index_module": "btcts.apps.operator_ui.hub.decision_policy_gate_visibility_completion_status_index",
        "status_index_builder": "build_decision_policy_gate_visibility_completion_status_index_packet",
        "source_dependencies": (
            "autotrade_decision_ledger_policy_gate_display",
            "decision_policy_gate_static_section_model",
            "decision_policy_gate_dashboard_status_index",
            "decision_policy_gate_visibility_chain_summary",
            "decision_policy_gate_visibility_chain_summary_registry_visibility",
            "decision_policy_gate_visibility_completion_checkpoint",
            "decision_policy_gate_visibility_completion_checkpoint_registry_visibility",
        ),
        "read_only_contract": True,
        "non_executing": True,
        "widget_reusable": True,
        "layout_decision_free": True,
        "data_model_only": True,
        "status_index_only": True,
        "visibility_completion_status_index_only": True,
        "not_runtime_payload_loading": True,
        "not_runtime_wiring": True,
        "not_ui_rendering": True,
        "no_command_buttons": True,
        "command_buttons_allowed": False,
        "forms_or_toggles_allowed": False,
        "runtime_wiring_allowed": False,
        "ui_rendering_implementation_allowed": False,
        "decision_append_allowed": False,
        "decision_ledger_integration_allowed": False,
        "live_shadow_behavior_change_allowed": False,
        "persist_true_allowed": False,
        "would_append_shadow_decision": False,
        "would_apply_mode": False,
        "would_execute_prearmed_grant": False,
        "would_write_runtime_artifact": False,
        "would_write_preview_status_artifact": False,
        "would_send_to_broker": False,
    },
    {
        "source_key": "decision_policy_gate_visibility_completion_checkpoint",
        "source_type": "decision_policy_gate_read_only_visibility_completion_checkpoint_packet",
        "consumer_scope": ("ai_tab", "prediction_tab", "health_tab", "future_widget"),
        "checkpoint_module": "btcts.apps.operator_ui.hub.decision_policy_gate_visibility_completion_checkpoint",
        "checkpoint_builder": "build_decision_policy_gate_visibility_completion_checkpoint_packet",
        "source_dependencies": (
            "autotrade_decision_ledger_policy_gate_display",
            "decision_policy_gate_static_section_model",
            "decision_policy_gate_dashboard_status_index",
            "decision_policy_gate_visibility_chain_summary",
            "decision_policy_gate_visibility_chain_summary_registry_visibility",
        ),
        "read_only_contract": True,
        "non_executing": True,
        "widget_reusable": True,
        "layout_decision_free": True,
        "data_model_only": True,
        "checkpoint_only": True,
        "visibility_completion_checkpoint_only": True,
        "not_runtime_payload_loading": True,
        "not_runtime_wiring": True,
        "not_ui_rendering": True,
        "no_command_buttons": True,
        "command_buttons_allowed": False,
        "forms_or_toggles_allowed": False,
        "runtime_wiring_allowed": False,
        "ui_rendering_implementation_allowed": False,
        "decision_append_allowed": False,
        "decision_ledger_integration_allowed": False,
        "live_shadow_behavior_change_allowed": False,
        "persist_true_allowed": False,
        "would_append_shadow_decision": False,
        "would_apply_mode": False,
        "would_execute_prearmed_grant": False,
        "would_write_runtime_artifact": False,
        "would_write_preview_status_artifact": False,
        "would_send_to_broker": False,
    },
    {
        "source_key": "decision_policy_gate_visibility_chain_summary",
        "source_type": "decision_policy_gate_read_only_visibility_chain_summary_packet",
        "consumer_scope": ("ai_tab", "prediction_tab", "health_tab", "future_widget"),
        "summary_module": "btcts.apps.operator_ui.hub.decision_policy_gate_visibility_chain_summary",
        "summary_builder": "build_decision_policy_gate_visibility_chain_summary_packet",
        "source_dependencies": (
            "autotrade_decision_ledger_policy_gate_display",
            "decision_policy_gate_static_section_model",
            "decision_policy_gate_dashboard_status_index",
            "decision_policy_gate_dashboard_status_index_registry_visibility",
        ),
        "read_only_contract": True,
        "non_executing": True,
        "widget_reusable": True,
        "layout_decision_free": True,
        "data_model_only": True,
        "summary_only": True,
        "visibility_summary_only": True,
        "not_runtime_payload_loading": True,
        "not_runtime_wiring": True,
        "not_ui_rendering": True,
        "no_command_buttons": True,
        "command_buttons_allowed": False,
        "forms_or_toggles_allowed": False,
        "runtime_wiring_allowed": False,
        "ui_rendering_implementation_allowed": False,
        "decision_append_allowed": False,
        "decision_ledger_integration_allowed": False,
        "live_shadow_behavior_change_allowed": False,
        "persist_true_allowed": False,
        "would_append_shadow_decision": False,
        "would_apply_mode": False,
        "would_execute_prearmed_grant": False,
        "would_write_runtime_artifact": False,
        "would_write_preview_status_artifact": False,
        "would_send_to_broker": False,
    },
    {
        "source_key": "decision_policy_gate_dashboard_status_index",
        "source_type": "decision_policy_gate_read_only_dashboard_status_index_packet",
        "consumer_scope": ("ai_tab", "prediction_tab", "health_tab", "future_widget"),
        "status_index_module": "btcts.apps.operator_ui.hub.decision_policy_gate_dashboard_status_index",
        "status_index_builder": "build_decision_policy_gate_dashboard_status_index_packet",
        "source_dependencies": (
            "autotrade_decision_ledger_policy_gate_display",
            "decision_policy_gate_dashboard_registry_visibility",
            "decision_policy_gate_static_section_model",
            "decision_policy_gate_static_section_registry_visibility",
        ),
        "read_only_contract": True,
        "non_executing": True,
        "widget_reusable": True,
        "layout_decision_free": True,
        "data_model_only": True,
        "status_index_only": True,
        "not_runtime_payload_loading": True,
        "not_runtime_wiring": True,
        "not_ui_rendering": True,
        "no_command_buttons": True,
        "command_buttons_allowed": False,
        "forms_or_toggles_allowed": False,
        "runtime_wiring_allowed": False,
        "ui_rendering_implementation_allowed": False,
        "decision_append_allowed": False,
        "decision_ledger_integration_allowed": False,
        "live_shadow_behavior_change_allowed": False,
        "persist_true_allowed": False,
        "would_append_shadow_decision": False,
        "would_apply_mode": False,
        "would_execute_prearmed_grant": False,
        "would_write_runtime_artifact": False,
        "would_write_preview_status_artifact": False,
        "would_send_to_broker": False,
    },
    {
        "source_key": "decision_policy_gate_static_section_model",
        "source_type": "decision_policy_gate_static_read_only_section_model",
        "consumer_scope": ("ai_tab", "prediction_tab", "health_tab", "future_widget"),
        "section_model_module": "btcts.apps.operator_ui.hub.decision_policy_gate_static_section_model",
        "section_model_builder": "build_decision_policy_gate_static_section_model",
        "source_dependencies": (
            "autotrade_decision_ledger_policy_gate_display",
            "decision_policy_gate_dashboard_registry_visibility",
            "decision_policy_gate_rendering_stub_policy_gate",
        ),
        "read_only_contract": True,
        "non_executing": True,
        "widget_reusable": True,
        "layout_decision_free": True,
        "data_model_only": True,
        "not_runtime_wiring": True,
        "not_ui_rendering": True,
        "no_command_buttons": True,
        "command_buttons_allowed": False,
        "forms_or_toggles_allowed": False,
        "runtime_wiring_allowed": False,
        "ui_rendering_implementation_allowed": False,
        "decision_append_allowed": False,
        "decision_ledger_integration_allowed": False,
        "live_shadow_behavior_change_allowed": False,
        "persist_true_allowed": False,
        "would_append_shadow_decision": False,
        "would_apply_mode": False,
        "would_execute_prearmed_grant": False,
        "would_write_runtime_artifact": False,
        "would_write_preview_status_artifact": False,
        "would_send_to_broker": False,
    },
    {
        "source_key": "autotrade_decision_ledger_policy_gate_display",
        "source_type": "autotrade_decision_ledger_policy_gate_display_packet",
        "consumer_scope": ("ai_tab", "prediction_tab", "health_tab", "future_widget"),
        "display_packet_module": "btcts.apps.operator_ui.components.autotrade_decision_ledger_policy_gate_display",
        "display_packet_builder": "build_autotrade_decision_ledger_policy_gate_display_packet",
        "read_only_contract": True,
        "widget_reusable": True,
        "layout_decision_free": True,
        "not_runtime_wiring": True,
        "not_ui_rendering": True,
        "no_command_buttons": True,
        "decision_append_allowed": False,
        "decision_ledger_integration_allowed": False,
        "live_shadow_behavior_change_allowed": False,
        "persist_true_allowed": False,
        "would_append_shadow_decision": False,
        "would_apply_mode": False,
        "would_execute_prearmed_grant": False,
        "would_write_runtime_artifact": False,
        "would_write_preview_status_artifact": False,
        "would_send_to_broker": False,
    },
    {
        "source_key": "summary_widget",
        "source_type": "execution_market_summary_widget_model",
        "consumer_scope": ("dashboard", "collector_tab", "warroom_tab", "health_tab", "future_widget"),
        "read_only_contract": True,
        "widget_reusable": True,
        "layout_decision_free": True,
    },
    {
        "source_key": "prediction_widget",
        "source_type": "execution_market_prediction_summary_widget_model",
        "consumer_scope": ("dashboard", "ai_tab", "prediction_tab", "future_widget"),
        "read_only_contract": True,
        "widget_reusable": True,
        "layout_decision_free": True,
    },
    {
        "source_key": "tactic_context",
        "source_type": "execution_market_prediction_tactic_context",
        "consumer_scope": ("ai_tab", "prediction_tab", "future_widget"),
        "read_only_contract": True,
        "widget_reusable": True,
        "layout_decision_free": True,
    },
    {
        "source_key": "review_hint_context",
        "source_type": "prediction_review_hint_summary_context",
        "consumer_scope": ("ai_tab", "prediction_tab", "position_tab", "execution_tab", "future_widget"),
        "read_only_contract": True,
        "widget_reusable": True,
        "layout_decision_free": True,
    },
    {
        "source_key": "review_hint_display",
        "source_type": "prediction_review_hint_display_context",
        "consumer_scope": ("ai_tab", "prediction_tab", "position_tab", "execution_tab", "future_widget"),
        "read_only_contract": True,
        "widget_reusable": True,
        "layout_decision_free": True,
    },
)


def load_operator_display_source_catalog() -> tuple[dict, ...]:
    return tuple(dict(item) for item in AI_OPERATOR_DISPLAY_SOURCE_CATALOG)



def load_operator_display_sources() -> dict:
    review_hint_context = load_prediction_review_hint_summary_payload()
    return {
        "summary_widget": load_execution_market_summary_widget_model(),
        "prediction_widget": load_execution_market_prediction_summary_widget_model(),
        "tactic_context": load_execution_market_prediction_tactic_proposal_payload(),
        "review_hint_context": review_hint_context,
        "review_hint_display": review_hint_display_sections(review_hint_context),
        "source_catalog": load_operator_display_source_catalog(),
    }
