# path: ./btcts_next/src/btcts/apps/operator_ui/ui_text.py
# desc: Operator UI の表示文言を集約し、英語/日本語の切り替えを提供する。

TEXTS = {
    "en": {
        "app_title": "BTC Trade System",
        "app_subtitle": "Project Chimera Operator Console",
        "sidebar_title": "Operator Panel",
        "sidebar_nav": "Navigate",
        "lang_label": "Language",
        "scale_label": "Font Scale",
        "page_collector": "Collector",
        "page_health": "Health",
        "page_logs": "Logs",
        "page_config": "Config",
        "collector_title": "Collector Status",
        "collector_metric_status": "Collector",
        "collector_metric_exchange": "Exchange",
        "collector_metric_eps": "Events/sec",
        "collector_status_running": "Running",
        "collector_status_connected": "Connected",
        "collector_status_live": "Live",
        "collector_recent_events": "Recent Events (WarRoom View)",
        "collector_no_events": "No events yet",
        "event_col_time": "Time",
        "event_col_event": "Event",
        "event_col_exchange": "Exchange",
        "event_col_topic": "Topic",
        "event_col_latency": "Latency(ms)",
        "event_col_bytes": "Bytes",
        "system_stats_title": "System Stats",
        "system_stats_not_found": "derived summary not found",
        "system_stats_load_error": "failed to load derived summary",
        "system_stats_http_total": "HTTP Total",
        "system_stats_http_429": "HTTP 429",
        "system_stats_restarts": "Restarts",
        "market_regime_title": "Market Regime",
        "market_regime_missing_data": "insufficient data for regime detection",
        "market_regime_orderbook_unavailable": "orderbook unavailable",
        "market_regime_regime": "Regime",
        "market_regime_spread_state": "Spread State",
        "market_regime_pressure": "Pressure",
        "market_regime_flow_agreement": "Flow Agreement",
        "market_regime_value_range": "RANGE",
        "market_regime_value_trend": "TREND",
        "market_regime_value_liquidity_vacuum": "LIQUIDITY VACUUM",
        "market_regime_value_volatility_expansion": "VOLATILITY EXPANSION",
        "market_regime_value_normal": "NORMAL",
        "market_regime_value_wide": "WIDE",
        "market_regime_value_tight": "TIGHT",
        "market_regime_value_neutral": "NEUTRAL",
        "market_regime_value_buy": "BUY",
        "market_regime_value_sell": "SELL",
        "market_regime_value_mixed": "MIXED",
        "market_regime_value_buy_confirm": "BUY CONFIRM",
        "market_regime_value_sell_confirm": "SELL CONFIRM",
        "market_monitor_title": "Market Monitor",
        "market_monitor_not_found": "orderbook data not found",
        "market_monitor_empty": "orderbook empty",
        "market_monitor_spread": "Spread",
        "market_monitor_bid_volume": "Bid Volume (Top10)",
        "market_monitor_ask_volume": "Ask Volume (Top10)",
        "market_monitor_imbalance": "Orderbook Imbalance",

        "liquidity_pressure_title": "Liquidity Pressure",
        "liquidity_pressure_not_found": "orderbook data not found",
        "liquidity_pressure_empty": "orderbook empty",
        "liquidity_pressure_top_bid_wall": "Top Bid Wall",
        "liquidity_pressure_top_ask_wall": "Top Ask Wall",
        "liquidity_pressure_wall_ratio": "Wall Ratio",
        "liquidity_pressure_wall_bias": "Wall Bias",
        "liquidity_pressure_value_neutral": "NEUTRAL",
        "liquidity_pressure_value_buy": "BUY",
        "liquidity_pressure_value_sell": "SELL",

        "trade_flow_title": "Trade Flow",
        "trade_flow_not_found": "trades data not found",
        "trade_flow_empty": "trade items empty",
        "trade_flow_buy_volume": "Buy Volume",
        "trade_flow_sell_volume": "Sell Volume",
        "trade_flow_delta": "Delta",
        "trade_flow_recent_count": "Recent trades",

        "ai_signal_title": "AI Signal",
        "ai_signal_missing_data": "insufficient data for AI signal",
        "ai_signal_orderbook_unavailable": "orderbook unavailable",
        "ai_signal_market_regime": "Market Regime",
        "ai_signal_orderbook_bias": "Orderbook Bias",
        "ai_signal_trade_delta": "Trade Delta",
        "ai_signal_decision": "AI Decision",
        "ai_signal_value_range": "RANGE",
        "ai_signal_value_trend": "TREND",
        "ai_signal_value_wait": "WAIT",
        "ai_signal_value_long_bias": "LONG BIAS",
        "ai_signal_value_short_bias": "SHORT BIAS",

        "strategy_state_title": "Strategy State",
        "strategy_state_missing_data": "insufficient data for strategy state",
        "strategy_state_unavailable": "strategy state unavailable",
        "strategy_state_mode": "Strategy Mode",
        "strategy_state_risk": "Risk State",
        "strategy_state_archetype": "Archetype",
        "strategy_state_confidence": "Confidence",
        "strategy_state_value_neutral": "NEUTRAL",
        "strategy_state_value_medium": "MEDIUM",
        "strategy_state_value_high": "HIGH",
        "strategy_state_value_low": "LOW",
        "strategy_state_value_long_trend": "LONG TREND",
        "strategy_state_value_short_trend": "SHORT TREND",
        "strategy_state_value_range_scalp": "RANGE SCALP",
        "strategy_state_value_volatility_watch": "VOLATILITY WATCH",
        "strategy_state_value_observe": "observe",
        "strategy_state_value_breakout": "breakout",
        "strategy_state_value_liquidity_trap": "liquidity_trap",
        "strategy_state_value_mean_reversion": "mean_reversion",
        "strategy_state_value_momentum_probe": "momentum_probe",

        "refresh_label": "Auto Refresh",
        "refresh_interval_label": "Refresh Interval (sec)",
        "refresh_status_on": "Auto refresh ON",
        "refresh_status_off": "Auto refresh OFF",

        "badge_liquidity_bias": "Liquidity Bias",
        "badge_ai_decision": "AI Decision",
        "badge_strategy_mode": "Strategy Mode",
        "badge_risk_state": "Risk State",

        "ai_summary_title": "AI Market Summary",
        "ai_summary_missing_data": "insufficient data for market summary",
        "ai_summary_headline": "Summary",
        "ai_summary_bullets": "Observations",
        "ai_summary_outlook": "Outlook",
        "ai_summary_value_buy_bias": "Buy bias is strengthening.",
        "ai_summary_value_sell_bias": "Sell bias is strengthening.",
        "ai_summary_value_neutral_bias": "Market bias is mixed.",
        "ai_summary_value_wide_spread": "Spread remains wide.",
        "ai_summary_value_tight_spread": "Spread remains tight.",
        "ai_summary_value_buy_flow": "Aggressive buyers are active.",
        "ai_summary_value_sell_flow": "Aggressive sellers are active.",
        "ai_summary_value_wait": "Wait for confirmation.",
        "ai_summary_value_long_watch": "Watch for long continuation.",
        "ai_summary_value_short_watch": "Watch for short continuation.",

        "ai_conversation_title": "AI Conversation",
        "ai_conversation_prompt": "Quick Prompt",
        "ai_conversation_note": "AI Note",
        "ai_conversation_result": "AI Response",
        "ai_conversation_placeholder": "Select a quick prompt to generate a local market explanation.",
        "ai_conversation_q1": "Summarize the current market.",
        "ai_conversation_q2": "Is short bias stronger now?",
        "ai_conversation_q3": "Is this wall likely fake or real?",
        "ai_conversation_q4": "Should we wait or prepare for breakout?",

        "ai_conversation_note_prefix": "Note",
        "ai_conversation_state": "Market Snapshot",
        "ai_conversation_state_spread": "Spread",
        "ai_conversation_state_imbalance": "Imbalance",
        "ai_conversation_state_delta": "Delta",
        "ai_conversation_state_wall_ratio": "Wall Ratio",

        "ai_conversation_custom_prompt": "Custom Prompt",
        "ai_conversation_send": "Send",
        "ai_conversation_history": "Conversation History",
        "ai_conversation_empty_history": "No conversation yet.",
        "ai_conversation_user": "You",
        "ai_conversation_ai": "AI",
        "strategy_state_value_observe_label": "observe",
        "strategy_state_value_breakout_label": "breakout",
        "strategy_state_value_liquidity_trap_label": "liquidity_trap",
        "strategy_state_value_mean_reversion_label": "mean_reversion",
        "strategy_state_value_momentum_probe_label": "momentum_probe",

        "ai_runtime_mode": "AI Runtime Mode",
        "ai_runtime_mode_local": "local",
        "ai_runtime_mode_external": "external",
        "ai_conversation_clear": "Clear History",
        "ai_conversation_clear_done": "Conversation history cleared.",

        "ai_runtime_external_disabled": "External AI mode is disabled",
        "ai_runtime_external_url_missing": "External AI URL is not configured",
        "ai_runtime_external_http_error": "External AI HTTP error",
        "ai_runtime_external_network_error": "External AI network error",
        "ai_runtime_external_timeout": "External AI request timed out",
        "ai_runtime_external_bad_response": "External AI returned invalid JSON",
        "ai_runtime_external_answer_missing": "External AI response does not contain a valid answer",
        "ai_runtime_fallback_prefix": "External AI failed, fallback to local",
        "ai_runtime_source": "Runtime Source",

        "ai_memory_title": "Market Memory",
        "ai_memory_empty": "No market memory yet.",
        "ai_memory_trend_improving": "improving",
        "ai_memory_trend_worsening": "worsening",
        "ai_memory_trend_stable": "stable",
        "ai_memory_spread_change": "Spread Change",
        "ai_memory_imbalance_change": "Imbalance Change",
        "ai_memory_delta_change": "Delta Change",
        "ai_memory_wall_ratio_change": "Wall Ratio Change",

        "ai_memory_persistent_hint": "Market memory is persisted in JSONL and survives UI reload.",

        "execution_feed_title": "Execution Feed",
        "execution_feed_empty": "No recent execution feed events.",
        "execution_feed_total": "Total Events",
        "execution_feed_avg_latency": "Avg Latency(ms)",
        "execution_feed_max_latency": "Max Latency(ms)",
        "execution_feed_status": "Feed Status",
        "execution_feed_orderbook": "Orderbook Events",
        "execution_feed_trades": "Trade Events",
        "execution_feed_rate_hold": "Rate Hold",
        "execution_feed_latest": "Latest Event",
        "execution_feed_status_empty": "EMPTY",
        "execution_feed_status_alert": "ALERT",
        "execution_feed_status_busy": "BUSY",
        "execution_feed_status_throttled": "THROTTLED",
        "execution_feed_status_normal": "NORMAL",

        "risk_monitor_title": "Risk Monitor",
        "risk_monitor_missing_data": "insufficient data for risk monitor",
        "risk_monitor_unavailable": "risk monitor data unavailable",
        "risk_monitor_overall": "Overall Risk",
        "risk_monitor_spread": "Spread Risk",
        "risk_monitor_latency": "Latency Risk",
        "risk_monitor_flow": "Flow Conflict",
        "risk_monitor_liquidity": "Liquidity Risk",
        "risk_monitor_value_low": "LOW",
        "risk_monitor_value_medium": "MEDIUM",
        "risk_monitor_value_high": "HIGH",
        "risk_monitor_badge_overall": "Overall Risk",
        "risk_monitor_badge_spread": "Spread Risk",
        "risk_monitor_badge_latency": "Latency Risk",
        "risk_monitor_snapshot": "Risk Snapshot",

        "page_research": "Research",
        "research_title": "Research Lab",
        "research_subtitle": "Explore short-term market memory, latency trend, and collector storage status.",
        "research_tab_memory": "Market Memory",
        "research_tab_latency": "Latency",
        "research_tab_storage": "Storage",
        "research_memory_title": "Market Memory History",
        "research_memory_empty": "No persisted market memory yet.",
        "research_memory_spread": "Spread",
        "research_memory_imbalance": "Imbalance",
        "research_memory_delta": "Delta",
        "research_memory_wall_ratio": "Wall Ratio",
        "research_latency_title": "Latency Trend",
        "research_latency_empty": "No latency rows available.",
        "research_latency_avg": "Avg Latency(ms)",
        "research_latency_max": "Max Latency(ms)",
        "research_latency_count": "Latency Rows",
        "research_storage_title": "Collector Storage Snapshot",
        "research_storage_orderbook": "Orderbook",
        "research_storage_trades": "Trades",
        "research_storage_file_count": "File Count",
        "research_storage_latest_file": "Latest File",
        "research_storage_latest_size": "Latest Size(MB)",

        "page_replay": "Replay",
        "replay_title": "Replay Lab",
        "replay_subtitle": "Review recent audit events and market memory as the foundation of future replay workflows.",
        "replay_tab_events": "Events",
        "replay_tab_memory": "Market Memory",
        "replay_tab_future": "Future Replay",
        "replay_events_title": "Recent Audit Events",
        "replay_events_empty": "No replayable events available.",
        "replay_events_count": "Event Count",
        "replay_events_avg_latency": "Avg Latency(ms)",
        "replay_events_max_latency": "Max Latency(ms)",
        "replay_memory_title": "Persisted Market Memory",
        "replay_memory_empty": "No persisted market memory available.",
        "replay_future_title": "Replay Roadmap",
        "replay_future_desc": "This space will evolve into a full replay workflow.",
        "replay_future_item_1": "Market timeline replay",
        "replay_future_item_2": "AI decision replay",
        "replay_future_item_3": "Strategy comparison replay",

        "ai_conversation_intent": "Intent",
        "ai_conversation_style": "Response Style",
        "ai_conversation_intent_explain": "Explain market",
        "ai_conversation_intent_decide": "Decision support",
        "ai_conversation_intent_risk": "Risk review",
        "ai_conversation_intent_wall": "Wall analysis",
        "ai_conversation_style_concise": "Concise",
        "ai_conversation_style_normal": "Normal",
        "ai_conversation_style_deep": "Deep",
        "ai_conversation_effective_prompt": "Effective Prompt",

        "research_memory_delta_from_prev": "Δ from Prev",
        "research_memory_regime_hint": "Research Hint",
        "research_memory_hint_trend": "Directional bias is expanding.",
        "research_memory_hint_range": "Bias remains mixed / range-like.",
        "research_latency_by_topic": "Latency by Topic",
        "research_latency_topic": "Topic",
        "research_latency_topic_avg": "Avg Latency(ms)",
        "research_latency_topic_count": "Rows",
        "research_storage_total_size": "Total Size(MB)",
    },
    "ja": {
        "app_title": "BTC Trade System",
        "app_subtitle": "Project Chimera オペレーターコンソール",
        "sidebar_title": "操作パネル",
        "sidebar_nav": "移動",
        "lang_label": "表示言語",
        "scale_label": "文字サイズ",
        "page_collector": "Collector",
        "page_health": "Health",
        "page_logs": "Logs",
        "page_config": "Config",
        "collector_title": "Collector 状態",
        "collector_metric_status": "Collector",
        "collector_metric_exchange": "取引所",
        "collector_metric_eps": "イベント/秒",
        "collector_status_running": "稼働中",
        "collector_status_connected": "接続中",
        "collector_status_live": "LIVE",
        "collector_recent_events": "最新イベント（WarRoom表示）",
        "collector_no_events": "イベントはまだありません",
        "event_col_time": "時刻",
        "event_col_event": "イベント",
        "event_col_exchange": "取引所",
        "event_col_topic": "トピック",
        "event_col_latency": "レイテンシ(ms)",
        "event_col_bytes": "Bytes",        
        "system_stats_title": "システム統計",
        "system_stats_not_found": "derived サマリが見つかりません",
        "system_stats_load_error": "derived サマリの読み込みに失敗しました",
        "system_stats_http_total": "HTTP総数",
        "system_stats_http_429": "HTTP 429",
        "system_stats_restarts": "再起動回数",
        "market_regime_title": "市場レジーム",
        "market_regime_missing_data": "レジーム判定に必要なデータが不足しています",
        "market_regime_orderbook_unavailable": "板データを利用できません",
        "market_regime_regime": "地合い",
        "market_regime_spread_state": "スプレッド状態",
        "market_regime_pressure": "圧力",
        "market_regime_flow_agreement": "フロー一致",
        "market_regime_value_range": "レンジ",
        "market_regime_value_trend": "トレンド",
        "market_regime_value_liquidity_vacuum": "流動性真空",
        "market_regime_value_volatility_expansion": "ボラ拡大",
        "market_regime_value_normal": "通常",
        "market_regime_value_wide": "広い",
        "market_regime_value_tight": "狭い",
        "market_regime_value_neutral": "中立",
        "market_regime_value_buy": "買い",
        "market_regime_value_sell": "売り",
        "market_regime_value_mixed": "混在",
        "market_regime_value_buy_confirm": "買い優勢確認",
        "market_regime_value_sell_confirm": "売り優勢確認",
        "market_monitor_title": "市場モニター",
        "market_monitor_not_found": "板データが見つかりません",
        "market_monitor_empty": "板データが空です",
        "market_monitor_spread": "スプレッド",
        "market_monitor_bid_volume": "買い板量(上位10)",
        "market_monitor_ask_volume": "売り板量(上位10)",
        "market_monitor_imbalance": "板バランス",

        "liquidity_pressure_title": "流動性圧力",
        "liquidity_pressure_not_found": "板データが見つかりません",
        "liquidity_pressure_empty": "板データが空です",
        "liquidity_pressure_top_bid_wall": "最大買い壁",
        "liquidity_pressure_top_ask_wall": "最大売り壁",
        "liquidity_pressure_wall_ratio": "壁比率",
        "liquidity_pressure_wall_bias": "壁バイアス",
        "liquidity_pressure_value_neutral": "中立",
        "liquidity_pressure_value_buy": "買い",
        "liquidity_pressure_value_sell": "売り",

        "trade_flow_title": "約定フロー",
        "trade_flow_not_found": "約定データが見つかりません",
        "trade_flow_empty": "約定データが空です",
        "trade_flow_buy_volume": "買い量",
        "trade_flow_sell_volume": "売り量",
        "trade_flow_delta": "デルタ",
        "trade_flow_recent_count": "直近約定数",

        "ai_signal_title": "AIシグナル",
        "ai_signal_missing_data": "AIシグナルに必要なデータが不足しています",
        "ai_signal_orderbook_unavailable": "板データを利用できません",
        "ai_signal_market_regime": "市場レジーム",
        "ai_signal_orderbook_bias": "板バイアス",
        "ai_signal_trade_delta": "約定デルタ",
        "ai_signal_decision": "AI判断",
        "ai_signal_value_range": "レンジ",
        "ai_signal_value_trend": "トレンド",
        "ai_signal_value_wait": "待機",
        "ai_signal_value_long_bias": "ロング寄り",
        "ai_signal_value_short_bias": "ショート寄り",

        "strategy_state_title": "戦略状態",
        "strategy_state_missing_data": "戦略状態に必要なデータが不足しています",
        "strategy_state_unavailable": "戦略状態を判定できません",
        "strategy_state_mode": "戦略モード",
        "strategy_state_risk": "リスク状態",
        "strategy_state_archetype": "アーキタイプ",
        "strategy_state_confidence": "信頼度",
        "strategy_state_value_neutral": "中立",
        "strategy_state_value_medium": "中",
        "strategy_state_value_high": "高",
        "strategy_state_value_low": "低",
        "strategy_state_value_long_trend": "上昇トレンド",
        "strategy_state_value_short_trend": "下降トレンド",
        "strategy_state_value_range_scalp": "レンジスキャルプ",
        "strategy_state_value_volatility_watch": "ボラ監視",
        "strategy_state_value_observe": "observe",
        "strategy_state_value_breakout": "breakout",
        "strategy_state_value_liquidity_trap": "liquidity_trap",
        "strategy_state_value_mean_reversion": "mean_reversion",
        "strategy_state_value_momentum_probe": "momentum_probe",

        "refresh_label": "自動更新",
        "refresh_interval_label": "更新間隔(秒)",
        "refresh_status_on": "自動更新 ON",
        "refresh_status_off": "自動更新 OFF",

        "badge_liquidity_bias": "流動性バイアス",
        "badge_ai_decision": "AI判断",
        "badge_strategy_mode": "戦略モード",
        "badge_risk_state": "リスク状態",

        "ai_summary_title": "AI市場サマリー",
        "ai_summary_missing_data": "市場サマリーに必要なデータが不足しています",
        "ai_summary_headline": "要約",
        "ai_summary_bullets": "観測ポイント",
        "ai_summary_outlook": "見通し",
        "ai_summary_value_buy_bias": "買いバイアスが強まりつつあります。",
        "ai_summary_value_sell_bias": "売りバイアスが強まりつつあります。",
        "ai_summary_value_neutral_bias": "市場バイアスは混在しています。",
        "ai_summary_value_wide_spread": "スプレッドは広い状態です。",
        "ai_summary_value_tight_spread": "スプレッドは狭い状態です。",
        "ai_summary_value_buy_flow": "積極的な買いフローが入っています。",
        "ai_summary_value_sell_flow": "積極的な売りフローが入っています。",
        "ai_summary_value_wait": "確証が出るまで待機が妥当です。",
        "ai_summary_value_long_watch": "上方向への継続を警戒します。",
        "ai_summary_value_short_watch": "下方向への継続を警戒します。",

        "ai_conversation_title": "AI会話パネル",
        "ai_conversation_prompt": "クイック質問",
        "ai_conversation_note": "AIメモ",
        "ai_conversation_result": "AI応答",
        "ai_conversation_placeholder": "クイック質問を選ぶと、現在の市場をローカル要約で説明します。",
        "ai_conversation_q1": "現在の市場を要約して",
        "ai_conversation_q2": "いまはショート優勢？",
        "ai_conversation_q3": "この壁は本物？フェイク？",
        "ai_conversation_q4": "待機すべき？ブレイク準備？",

        "ai_conversation_note_prefix": "メモ",
        "ai_conversation_state": "市場スナップショット",
        "ai_conversation_state_spread": "スプレッド",
        "ai_conversation_state_imbalance": "板バランス",
        "ai_conversation_state_delta": "約定デルタ",
        "ai_conversation_state_wall_ratio": "壁比率",

        "ai_conversation_custom_prompt": "自由入力",
        "ai_conversation_send": "送信",
        "ai_conversation_history": "会話履歴",
        "ai_conversation_empty_history": "会話履歴はまだありません。",
        "ai_conversation_user": "あなた",
        "ai_conversation_ai": "AI",
        "strategy_state_value_observe_label": "観察",
        "strategy_state_value_breakout_label": "ブレイクアウト",
        "strategy_state_value_liquidity_trap_label": "流動性トラップ",
        "strategy_state_value_mean_reversion_label": "平均回帰",
        "strategy_state_value_momentum_probe_label": "モメンタム探索",

        "ai_runtime_mode": "AI実行モード",
        "ai_runtime_mode_local": "local",
        "ai_runtime_mode_external": "external",
        "ai_conversation_clear": "履歴クリア",
        "ai_conversation_clear_done": "会話履歴をクリアしました。",

        "ai_runtime_external_disabled": "external AI モードは無効です",
        "ai_runtime_external_url_missing": "external AI の URL が未設定です",
        "ai_runtime_external_http_error": "external AI HTTP エラー",
        "ai_runtime_external_network_error": "external AI 接続エラー",
        "ai_runtime_external_timeout": "external AI の応答がタイムアウトしました",
        "ai_runtime_external_bad_response": "external AI から不正な JSON が返りました",
        "ai_runtime_external_answer_missing": "external AI 応答に有効な answer がありません",
        "ai_runtime_fallback_prefix": "external AI 失敗のため local にフォールバック",
        "ai_runtime_source": "実行ソース",

        "ai_memory_title": "市場状態メモリ",
        "ai_memory_empty": "市場状態メモリはまだありません。",
        "ai_memory_trend_improving": "改善",
        "ai_memory_trend_worsening": "悪化",
        "ai_memory_trend_stable": "安定",
        "ai_memory_spread_change": "スプレッド変化",
        "ai_memory_imbalance_change": "板バランス変化",
        "ai_memory_delta_change": "約定デルタ変化",
        "ai_memory_wall_ratio_change": "壁比率変化",

        "ai_memory_persistent_hint": "市場状態メモリは JSONL に保存され、UI再読込後も保持されます。",

        "execution_feed_title": "Execution Feed",
        "execution_feed_empty": "直近の Execution Feed イベントがありません。",
        "execution_feed_total": "総イベント数",
        "execution_feed_avg_latency": "平均レイテンシ(ms)",
        "execution_feed_max_latency": "最大レイテンシ(ms)",
        "execution_feed_status": "Feed状態",
        "execution_feed_orderbook": "Orderbook件数",
        "execution_feed_trades": "Trades件数",
        "execution_feed_rate_hold": "Rate Hold件数",
        "execution_feed_latest": "最新イベント",
        "execution_feed_status_empty": "空",
        "execution_feed_status_alert": "警戒",
        "execution_feed_status_busy": "高負荷",
        "execution_feed_status_throttled": "抑制中",
        "execution_feed_status_normal": "正常",

        "risk_monitor_title": "Risk Monitor",
        "risk_monitor_missing_data": "Risk Monitor に必要なデータが不足しています",
        "risk_monitor_unavailable": "Risk Monitor のデータを取得できません",
        "risk_monitor_overall": "総合リスク",
        "risk_monitor_spread": "スプレッドリスク",
        "risk_monitor_latency": "レイテンシリスク",
        "risk_monitor_flow": "フロー衝突",
        "risk_monitor_liquidity": "流動性リスク",
        "risk_monitor_value_low": "低",
        "risk_monitor_value_medium": "中",
        "risk_monitor_value_high": "高",
        "risk_monitor_badge_overall": "総合リスク",
        "risk_monitor_badge_spread": "スプレッドリスク",
        "risk_monitor_badge_latency": "レイテンシリスク",
        "risk_monitor_snapshot": "リスクスナップショット",

        "agent_panels_title": "AI Agents",
        "agent_panels_missing_data": "insufficient data for AI agent panels",
        "agent_panels_unavailable": "AI agent data unavailable",
        "agent_panels_snapshot": "Agent Snapshot",

        "agent_analyst_title": "Analyst AI",
        "agent_analyst_regime": "Regime",
        "agent_analyst_spread": "Spread State",
        "agent_analyst_pressure": "Pressure",

        "agent_strategy_title": "Strategy AI",
        "agent_strategy_archetype": "Archetype",
        "agent_strategy_stance": "Stance",
        "agent_strategy_delta": "Trade Delta",

        "agent_risk_title": "Risk AI",
        "agent_risk_level": "Risk Level",
        "agent_risk_latency": "Avg Latency(ms)",
        "agent_risk_wall_ratio": "Wall Ratio",

        "agent_value_range": "RANGE",
        "agent_value_trend": "TREND",
        "agent_value_normal": "NORMAL",
        "agent_value_wide": "WIDE",
        "agent_value_tight": "TIGHT",
        "agent_value_neutral": "NEUTRAL",
        "agent_value_buy": "BUY",
        "agent_value_sell": "SELL",
        "agent_value_wait": "WAIT",
        "agent_value_prepare": "PREPARE",
        "agent_value_long_bias": "LONG BIAS",
        "agent_value_short_bias": "SHORT BIAS",
        "agent_value_observe": "observe",
        "agent_value_breakout": "breakout",
        "agent_value_liquidity_trap": "liquidity_trap",
        "agent_value_mean_reversion": "mean_reversion",
        "agent_value_momentum_probe": "momentum_probe",
        "agent_value_low": "LOW",
        "agent_value_medium": "MEDIUM",
        "agent_value_high": "HIGH",

        "agent_panels_title": "AIエージェント",
        "agent_panels_missing_data": "AIエージェント表示に必要なデータが不足しています",
        "agent_panels_unavailable": "AIエージェントのデータを取得できません",
        "agent_panels_snapshot": "エージェントスナップショット",

        "agent_analyst_title": "Analyst AI",
        "agent_analyst_regime": "地合い",
        "agent_analyst_spread": "スプレッド状態",
        "agent_analyst_pressure": "圧力",

        "agent_strategy_title": "Strategy AI",
        "agent_strategy_archetype": "アーキタイプ",
        "agent_strategy_stance": "スタンス",
        "agent_strategy_delta": "約定デルタ",

        "agent_risk_title": "Risk AI",
        "agent_risk_level": "リスク水準",
        "agent_risk_latency": "平均レイテンシ(ms)",
        "agent_risk_wall_ratio": "壁比率",

        "agent_value_range": "レンジ",
        "agent_value_trend": "トレンド",
        "agent_value_normal": "通常",
        "agent_value_wide": "広い",
        "agent_value_tight": "狭い",
        "agent_value_neutral": "中立",
        "agent_value_buy": "買い",
        "agent_value_sell": "売り",
        "agent_value_wait": "待機",
        "agent_value_prepare": "準備",
        "agent_value_long_bias": "ロング寄り",
        "agent_value_short_bias": "ショート寄り",
        "agent_value_observe": "観察",
        "agent_value_breakout": "ブレイクアウト",
        "agent_value_liquidity_trap": "流動性トラップ",
        "agent_value_mean_reversion": "平均回帰",
        "agent_value_momentum_probe": "モメンタム探索",
        "agent_value_low": "低",
        "agent_value_medium": "中",
        "agent_value_high": "高",

        "page_research": "Research",
        "research_title": "Research Lab",
        "research_subtitle": "短期の市場状態メモリ、レイテンシ傾向、collector 保存状況を確認します。",
        "research_tab_memory": "市場状態メモリ",
        "research_tab_latency": "レイテンシ",
        "research_tab_storage": "保存状況",
        "research_memory_title": "市場状態メモリ履歴",
        "research_memory_empty": "永続化された市場状態メモリはまだありません。",
        "research_memory_spread": "スプレッド",
        "research_memory_imbalance": "板バランス",
        "research_memory_delta": "約定デルタ",
        "research_memory_wall_ratio": "壁比率",
        "research_latency_title": "レイテンシ傾向",
        "research_latency_empty": "レイテンシ行がありません。",
        "research_latency_avg": "平均レイテンシ(ms)",
        "research_latency_max": "最大レイテンシ(ms)",
        "research_latency_count": "レイテンシ件数",
        "research_storage_title": "Collector 保存状況",
        "research_storage_orderbook": "Orderbook",
        "research_storage_trades": "Trades",
        "research_storage_file_count": "ファイル数",
        "research_storage_latest_file": "最新ファイル",
        "research_storage_latest_size": "最新サイズ(MB)",

        "page_replay": "Replay",
        "replay_title": "Replay Lab",
        "replay_subtitle": "直近の audit イベントと市場状態メモリを見返し、将来の replay 機能の土台を確認します。",
        "replay_tab_events": "イベント",
        "replay_tab_memory": "市場状態メモリ",
        "replay_tab_future": "将来の Replay",
        "replay_events_title": "直近 audit イベント",
        "replay_events_empty": "再確認できるイベントがありません。",
        "replay_events_count": "イベント数",
        "replay_events_avg_latency": "平均レイテンシ(ms)",
        "replay_events_max_latency": "最大レイテンシ(ms)",
        "replay_memory_title": "永続化された市場状態メモリ",
        "replay_memory_empty": "永続化された市場状態メモリはありません。",
        "replay_future_title": "Replay ロードマップ",
        "replay_future_desc": "この空間は将来、完全な replay ワークフローへ進化します。",
        "replay_future_item_1": "市場タイムライン replay",
        "replay_future_item_2": "AI判断 replay",
        "replay_future_item_3": "戦略比較 replay",

        "ai_conversation_intent": "質問意図",
        "ai_conversation_style": "応答スタイル",
        "ai_conversation_intent_explain": "市場説明",
        "ai_conversation_intent_decide": "判断補助",
        "ai_conversation_intent_risk": "リスク確認",
        "ai_conversation_intent_wall": "壁分析",
        "ai_conversation_style_concise": "簡潔",
        "ai_conversation_style_normal": "通常",
        "ai_conversation_style_deep": "詳細",
        "ai_conversation_effective_prompt": "実効プロンプト",

        "research_memory_delta_from_prev": "前回差分",
        "research_memory_regime_hint": "研究ヒント",
        "research_memory_hint_trend": "方向性バイアスが拡大しています。",
        "research_memory_hint_range": "バイアスは混在しておりレンジ寄りです。",
        "research_latency_by_topic": "topic別レイテンシ",
        "research_latency_topic": "topic",
        "research_latency_topic_avg": "平均レイテンシ(ms)",
        "research_latency_topic_count": "件数",
        "research_storage_total_size": "合計サイズ(MB)",
    },
}


def get_text(lang: str, key: str) -> str:

    if lang not in TEXTS:
        lang = "en"

    return TEXTS[lang].get(key, key)