# path: ./btcts_next/src/btcts/apps/operator_ui/ui_text.py
# desc: Operator UI の表示文言を集約し、英語/日本語の切り替えを提供する。

from btcts.apps.operator_ui.texts import TEXTS as SPLIT_TEXTS

TEXTS = {
    "en": {
        "system_stats_not_found": "derived summary not found",
        "system_stats_load_error": "failed to load derived summary",
        "system_stats_http_total": "HTTP Total",
        "system_stats_http_429": "HTTP 429",
        "system_stats_restarts": "Restarts",

        "ai_signal_missing_data": "insufficient data for AI signal",
        "ai_signal_orderbook_unavailable": "orderbook unavailable",
        "ai_signal_market_regime": "Market Regime",
        "ai_signal_orderbook_bias": "Orderbook Bias",
        "ai_signal_trade_delta": "Trade Delta",
        "ai_signal_decision": "AI Decision",
        "ai_signal_value_range": "RANGE",
        "ai_signal_value_trend": "TREND",
        "ai_signal_value_wait": "WAIT",
        "ai_signal_value_long_bias": "LONG BIAS",
        "ai_signal_value_short_bias": "SHORT BIAS",

        "strategy_state_missing_data": "insufficient data for strategy state",
        "strategy_state_unavailable": "strategy state unavailable",
        "strategy_state_mode": "Strategy Mode",
        "strategy_state_risk": "Risk State",
        "strategy_state_archetype": "Archetype",
        "strategy_state_confidence": "Confidence",
        "strategy_state_value_neutral": "NEUTRAL",
        "strategy_state_value_medium": "MEDIUM",
        "strategy_state_value_high": "HIGH",
        "strategy_state_value_low": "LOW",
        "strategy_state_value_long_trend": "LONG TREND",
        "strategy_state_value_short_trend": "SHORT TREND",
        "strategy_state_value_range_scalp": "RANGE SCALP",
        "strategy_state_value_volatility_watch": "VOLATILITY WATCH",
        "strategy_state_value_observe": "observe",
        "strategy_state_value_breakout": "breakout",
        "strategy_state_value_liquidity_trap": "liquidity_trap",
        "strategy_state_value_mean_reversion": "mean_reversion",
        "strategy_state_value_momentum_probe": "momentum_probe",

        "badge_ai_decision": "AI Decision",
        "badge_strategy_mode": "Strategy Mode",
        "badge_risk_state": "Risk State",

        "ai_summary_title": "AI Market Summary",
        "ai_summary_missing_data": "insufficient data for market summary",
        "ai_summary_headline": "Summary",
        "ai_summary_bullets": "Observations",
        "ai_summary_outlook": "Outlook",
        "ai_summary_value_buy_bias": "Buy bias is strengthening.",
        "ai_summary_value_sell_bias": "Sell bias is strengthening.",
        "ai_summary_value_neutral_bias": "Market bias is mixed.",
        "ai_summary_value_wide_spread": "Spread remains wide.",
        "ai_summary_value_tight_spread": "Spread remains tight.",
        "ai_summary_value_buy_flow": "Aggressive buyers are active.",
        "ai_summary_value_sell_flow": "Aggressive sellers are active.",
        "ai_summary_value_wait": "Wait for confirmation.",
        "ai_summary_value_long_watch": "Watch for long continuation.",
        "ai_summary_value_short_watch": "Watch for short continuation.",

        "ai_conversation_title": "AI Conversation",
        "ai_conversation_prompt": "Quick Prompt",
        "ai_conversation_note": "AI Note",
        "ai_conversation_result": "AI Response",
        "ai_conversation_placeholder": "Select a quick prompt to generate a local market explanation.",
        "ai_conversation_q1": "Summarize the current market.",
        "ai_conversation_q2": "Is short bias stronger now?",
        "ai_conversation_q3": "Is this wall likely fake or real?",
        "ai_conversation_q4": "Should we wait or prepare for breakout?",

        "ai_conversation_note_prefix": "Note",
        "ai_conversation_state": "Market Snapshot",
        "ai_conversation_state_spread": "Spread",
        "ai_conversation_state_imbalance": "Imbalance",
        "ai_conversation_state_delta": "Delta",
        "ai_conversation_state_wall_ratio": "Wall Ratio",

        "ai_conversation_custom_prompt": "Custom Prompt",
        "ai_conversation_send": "Send",
        "ai_conversation_history": "Conversation History",
        "ai_conversation_empty_history": "No conversation yet.",
        "ai_conversation_user": "You",
        "ai_conversation_ai": "AI",
        "strategy_state_value_observe_label": "observe",
        "strategy_state_value_breakout_label": "breakout",
        "strategy_state_value_liquidity_trap_label": "liquidity_trap",
        "strategy_state_value_mean_reversion_label": "mean_reversion",
        "strategy_state_value_momentum_probe_label": "momentum_probe",

        "ai_runtime_mode": "AI Runtime Mode",
        "ai_runtime_mode_local": "local",
        "ai_runtime_mode_external": "external",
        "ai_conversation_clear": "Clear History",
        "ai_conversation_clear_done": "Conversation history cleared.",

        "ai_runtime_external_disabled": "External AI mode is disabled",
        "ai_runtime_external_url_missing": "External AI URL is not configured",
        "ai_runtime_external_http_error": "External AI HTTP error",
        "ai_runtime_external_network_error": "External AI network error",
        "ai_runtime_external_timeout": "External AI request timed out",
        "ai_runtime_external_bad_response": "External AI returned invalid JSON",
        "ai_runtime_external_answer_missing": "External AI response does not contain a valid answer",
        "ai_runtime_fallback_prefix": "External AI failed, fallback to local",
        "ai_runtime_source": "Runtime Source",

        "ai_memory_title": "Market Memory",
        "ai_memory_empty": "No market memory yet.",
        "ai_memory_trend_improving": "improving",
        "ai_memory_trend_worsening": "worsening",
        "ai_memory_trend_stable": "stable",
        "ai_memory_spread_change": "Spread Change",
        "ai_memory_imbalance_change": "Imbalance Change",
        "ai_memory_delta_change": "Delta Change",
        "ai_memory_wall_ratio_change": "Wall Ratio Change",
        "ai_memory_persistent_hint": "Market memory is persisted in JSONL and survives UI reload.",

        "execution_feed_status_empty": "EMPTY",
        "execution_feed_status_alert": "ALERT",
        "execution_feed_status_busy": "BUSY",
        "execution_feed_status_throttled": "THROTTLED",
        "execution_feed_status_normal": "NORMAL",

        "ai_conversation_intent": "Intent",
        "ai_conversation_style": "Response Style",
        "ai_conversation_intent_explain": "Explain market",
        "ai_conversation_intent_decide": "Decision support",
        "ai_conversation_intent_risk": "Risk review",
        "ai_conversation_intent_wall": "Wall analysis",
        "ai_conversation_style_concise": "Concise",
        "ai_conversation_style_normal": "Normal",
        "ai_conversation_style_deep": "Deep",
        "ai_conversation_effective_prompt": "Effective Prompt",

        "research_memory_delta_from_prev": "Δ from Prev",
        "research_memory_regime_hint": "Research Hint",
        "research_memory_hint_trend": "Directional bias is expanding.",
        "research_memory_hint_range": "Bias remains mixed / range-like.",
        "research_latency_by_topic": "Latency by Topic",
        "research_latency_topic": "Topic",
        "research_latency_topic_avg": "Avg Latency(ms)",
        "research_latency_topic_count": "Rows",
        "research_storage_total_size": "Total Size(MB)",

        "warroom_header_title": "War Room Situation",
        "warroom_header_missing_data": "War Room header data is not available.",
        "warroom_header_regime": "Market Regime",
        "warroom_header_spread_state": "Spread State",
        "warroom_header_pressure": "Pressure",
        "warroom_header_trade_flow": "Trade Flow",
        "warroom_header_ai_decision": "AI Decision",
        "warroom_header_risk": "Risk",

        "ai_reasoning_title": "AI Reasoning",
        "ai_reasoning_missing_data": "AI reasoning data is not available.",
        "ai_reasoning_reasons": "Why AI thinks so",
        "ai_reasoning_conclusion": "Conclusion",
        "ai_reasoning_headline_long": "AI sees conditions supportive of a long-side continuation.",
        "ai_reasoning_headline_short": "AI sees conditions supportive of a short-side continuation.",
        "ai_reasoning_headline_buy_pressure": "AI sees buy-side pressure building.",
        "ai_reasoning_headline_sell_pressure": "AI sees sell-side pressure building.",
        "ai_reasoning_headline_wait": "AI sees mixed conditions and prefers caution.",
        "ai_reasoning_reason_spread_wide": "Spread is wide, so execution quality is less stable.",
        "ai_reasoning_reason_spread_tight": "Spread is tight, so execution conditions are relatively efficient.",
        "ai_reasoning_reason_spread_normal": "Spread is in a normal range.",
        "ai_reasoning_reason_bid_bias": "Orderbook shows bid-side dominance.",
        "ai_reasoning_reason_ask_bias": "Orderbook shows ask-side dominance.",
        "ai_reasoning_reason_balance_mixed": "Orderbook balance is mixed.",
        "ai_reasoning_reason_buy_flow": "Trade flow is tilted to buys.",
        "ai_reasoning_reason_sell_flow": "Trade flow is tilted to sells.",
        "ai_reasoning_reason_flow_mixed": "Trade flow remains mixed.",
        "ai_reasoning_reason_bid_wall": "Bid wall is visible and may support downside absorption.",
        "ai_reasoning_reason_ask_wall": "Ask wall is visible and may cap upside continuation.",
        "ai_reasoning_conclusion_long_watch": "Monitor long continuation, but confirm persistence first.",
        "ai_reasoning_conclusion_short_watch": "Monitor short continuation, but confirm persistence first.",
        "ai_reasoning_conclusion_wall_risk": "Wall imbalance is strong, so trap risk should be watched carefully.",
        "ai_reasoning_conclusion_wait": "Current conditions still favor waiting for clearer confirmation.",

        "warroom_alert_empty": "No important alerts detected right now.",
        "warroom_alert_caption": "Alerts are derived from replay / research artifacts and recent audit latency.",
        "ui_label_guide": "Guide",
        "ui_label_overview": "Overview",
        "ui_label_operator_support": "Operator Support",
        "ui_label_primary_live": "Primary Live",
        "ui_label_ai_diagnostics": "AI Diagnostics",
        "ui_label_unified_supervisor": "Unified Supervisor",
        "ui_label_rate_control": "Rate Control",
        "ui_label_origin_continuity": "Origin Continuity",
        "ui_label_origin_continuity_audit": "Origin Continuity Audit",
        "ui_label_collector_runtime_state": "Collector Runtime State",
        "ui_label_raw_origin_status_json": "Raw origin_status JSON",
        "ui_label_ws_continuity_origin_status": "WS Continuity (origin_status)",
        "ui_label_daemon_supervisor_health": "Daemon / Supervisor Health",
        "ui_label_raw_rate_state_json": "Raw Rate State JSON",
        "ui_label_archive_retention_diagnostics": "Archive / Retention Diagnostics",
        "ui_label_archive_latest_copy": "Latest Copy 5",
        "ui_label_archive_latest_delete": "Latest Delete 5",
        "ui_label_archive_hot_remaining": "Hot D drive remaining data files (latest 50)",
        "collector_metric_continuity_status": "Continuity Status",
        "collector_metric_ws_state": "WS State",
        "collector_metric_snapshot_to_live_ms": "Snapshot→LIVE (ms)",
        "collector_metric_resync_occurred": "Resync Occurred",
        "collector_metric_dropped_pre_snapshot_deltas": "Dropped Pre-Snapshot Deltas",
        "collector_metric_origin_age_sec": "Origin Age (sec)",
        "collector_metric_gap_detected": "Gap Detected",
        "collector_metric_resync_started": "Resync Started",
        "collector_metric_resync_completed": "Resync Completed",
        "collector_metric_resync_complete_ratio": "Resync Complete Ratio",
        "collector_metric_copy_mode": "Copy Mode",
        "collector_metric_gc_mode": "GC Mode",
        "collector_metric_gc_enabled": "GC Enabled",
        "collector_metric_gc_dry_run": "GC Dry Run",
        "collector_metric_remaining_hot_files": "Remaining Hot Files",
        "collector_metric_supervisor_mode": "Supervisor Mode",
        "collector_metric_pending_request": "Pending Request",
        "collector_metric_supervisor_uptime_sec": "Supervisor Uptime (sec)",
        "collector_metric_rate_posture": "Rate Posture",
        "collector_metric_recent_429": "Recent 429",
        "collector_metric_rate_summary": "Rate Summary",
        "collector_metric_wait_ms": "Wait (ms)",
        "collector_metric_util_ratio": "Util Ratio",
        "collector_metric_recovery": "Recovery",
        "collector_metric_status_freshness": "Status Freshness",
        "collector_metric_status_age_sec": "Status Age (sec)",
        "collector_metric_origin_ws_state": "Origin WS State",
        "collector_metric_origin_snapshot_to_live_ms": "Origin Snapshot→LIVE (ms)",
        "collector_metric_origin_pre_snapshot_drops": "Origin Pre-Snapshot Drops",
        "collector_msg_watchdog_not_running": "watchdog is not RUNNING. request file can be written, but restart may not execute yet.",
        "collector_msg_restart_pending": "restart request is already pending. wait for watchdog to consume it before reissuing.",
        "collector_msg_supervisor_status_unavailable": "unified supervisor status not available",
        "collector_msg_rate_state_unavailable": "rate_state.json not available",
        "collector_msg_recent_429_detected": "recent 429 detected",
        "collector_msg_rate_posture_normal": "rate posture normal",
        "collector_msg_rate_control_engaged": "rate control engaged",
        "collector_msg_origin_status_unavailable": "origin_status.json not available",
        "collector_msg_daemon_health_unavailable": "daemon health state not available",
        "collector_msg_latest_copy_unavailable": "latest copy history not available",
        "collector_msg_latest_delete_unavailable": "latest delete history not available",
        "collector_msg_hot_remaining_unavailable": "hot remaining data files not available",
        "collector_msg_status_origin_unavailable": "status.json origin_continuity not available",
        "collector_caption_reason_line": "reason={reason} / live_mode={live_mode} / health={health} / daemon={daemon} / cycle_last_sequence_id={sequence_id}",
        "collector_caption_supervisor_line": "supervisor_mode={mode} / last_action={last_action} / last_error={last_error}",
        "collector_caption_pending_request_line": "pending_request={action} / requested_by={requested_by} / reason={reason}",
        "collector_caption_daemon_stop_line": "daemon_stop_request={action} / requested_by={requested_by}",
        "collector_caption_age_line": "age status={status_age} / health={health_age} / daemon={daemon_age} / checkpoint={checkpoint_age}",
        "collector_caption_state_dir_line": "state_dir={path}",
        "collector_caption_ui_roots_line": "ui_data_root={data_root} / ui_logs_root={logs_root} / ui_market_state_root={market_state_root}",
        "collector_caption_archive_started_line": "archive_started_at={started_at} / copy_last_scan_ts={copy_last_scan_ts} / gc_last_scan_ts={gc_last_scan_ts}",
        "collector_caption_archive_counts_line": "copy_last_plan_count={copy_plan_count} / copy_last_copied_files={copy_copied_files} / gc_last_plan_count={gc_plan_count} / gc_last_deleted_files={gc_deleted_files}",
        "collector_caption_archive_audit_path_line": "archive_audit_path={audit_path}",
        "ui_slot_diagnostics_title": "UI Slot Diagnostics",
        "ui_slot_diagnostics_health_caption": "health page slot registry / refresh_mode and priority draft",
        "ui_slot_registry_empty_health": "health slot registry is empty",
        "health_label_range_selector": "Range",
        "health_range_1h": "1h",
        "health_range_24h": "24h",
        "health_range_1w": "1w",
        "health_event_ws_exec_started": "ws executions started",
        "health_event_ws_exec_connected": "ws executions connected",
        "health_event_ws_exec_reconnected": "ws executions reconnected",
        "health_event_ws_exec_message_received": "ws executions message received",
        "health_event_ws_exec_message_skipped": "ws executions message skipped",
        "health_event_ws_exec_meta": "ws executions meta event",
        "health_event_ws_exec_trade_written": "ws executions trade written",

    },
    "ja": {
        "system_stats_not_found": "derived サマリが見つかりません",
        "system_stats_load_error": "derived サマリの読み込みに失敗しました",
        "system_stats_http_total": "HTTP総数",
        "system_stats_http_429": "HTTP 429",
        "system_stats_restarts": "再起動回数",

        "ai_signal_missing_data": "AIシグナルに必要なデータが不足しています",
        "ai_signal_orderbook_unavailable": "板データを利用できません",
        "ai_signal_market_regime": "市場レジーム",
        "ai_signal_orderbook_bias": "板バイアス",
        "ai_signal_trade_delta": "約定デルタ",
        "ai_signal_decision": "AI判断",
        "ai_signal_value_range": "レンジ",
        "ai_signal_value_trend": "トレンド",
        "ai_signal_value_wait": "待機",
        "ai_signal_value_long_bias": "ロング寄り",
        "ai_signal_value_short_bias": "ショート寄り",

        "strategy_state_missing_data": "戦略状態に必要なデータが不足しています",
        "strategy_state_unavailable": "戦略状態を判定できません",
        "strategy_state_mode": "戦略モード",
        "strategy_state_risk": "リスク状態",
        "strategy_state_archetype": "アーキタイプ",
        "strategy_state_confidence": "信頼度",
        "strategy_state_value_neutral": "中立",
        "strategy_state_value_medium": "中",
        "strategy_state_value_high": "高",
        "strategy_state_value_low": "低",
        "strategy_state_value_long_trend": "上昇トレンド",
        "strategy_state_value_short_trend": "下降トレンド",
        "strategy_state_value_range_scalp": "レンジスキャルプ",
        "strategy_state_value_volatility_watch": "ボラ監視",
        "strategy_state_value_observe": "observe",
        "strategy_state_value_breakout": "breakout",
        "strategy_state_value_liquidity_trap": "liquidity_trap",
        "strategy_state_value_mean_reversion": "mean_reversion",
        "strategy_state_value_momentum_probe": "momentum_probe",

        "badge_ai_decision": "AI判断",
        "badge_strategy_mode": "戦略モード",
        "badge_risk_state": "リスク状態",

        "ai_summary_title": "AI市場サマリー",
        "ai_summary_missing_data": "市場サマリーに必要なデータが不足しています",
        "ai_summary_headline": "要約",
        "ai_summary_bullets": "観測ポイント",
        "ai_summary_outlook": "見通し",
        "ai_summary_value_buy_bias": "買いバイアスが強まりつつあります。",
        "ai_summary_value_sell_bias": "売りバイアスが強まりつつあります。",
        "ai_summary_value_neutral_bias": "市場バイアスは混在しています。",
        "ai_summary_value_wide_spread": "スプレッドは広い状態です。",
        "ai_summary_value_tight_spread": "スプレッドは狭い状態です。",
        "ai_summary_value_buy_flow": "積極的な買いフローが入っています。",
        "ai_summary_value_sell_flow": "積極的な売りフローが入っています。",
        "ai_summary_value_wait": "確証が出るまで待機が妥当です。",
        "ai_summary_value_long_watch": "上方向への継続を警戒します。",
        "ai_summary_value_short_watch": "下方向への継続を警戒します。",

        "ai_conversation_title": "AI会話パネル",
        "ai_conversation_prompt": "クイック質問",
        "ai_conversation_note": "AIメモ",
        "ai_conversation_result": "AI応答",
        "ai_conversation_placeholder": "クイック質問を選ぶと、現在の市場をローカル要約で説明します。",
        "ai_conversation_q1": "現在の市場を要約して",
        "ai_conversation_q2": "いまはショート優勢？",
        "ai_conversation_q3": "この壁は本物？フェイク？",
        "ai_conversation_q4": "待機すべき？ブレイク準備？",

        "ai_conversation_note_prefix": "メモ",
        "ai_conversation_state": "市場スナップショット",
        "ai_conversation_state_spread": "スプレッド",
        "ai_conversation_state_imbalance": "板バランス",
        "ai_conversation_state_delta": "約定デルタ",
        "ai_conversation_state_wall_ratio": "壁比率",

        "ai_conversation_custom_prompt": "自由入力",
        "ai_conversation_send": "送信",
        "ai_conversation_history": "会話履歴",
        "ai_conversation_empty_history": "会話履歴はまだありません。",
        "ai_conversation_user": "あなた",
        "ai_conversation_ai": "AI",
        "strategy_state_value_observe_label": "観察",
        "strategy_state_value_breakout_label": "ブレイクアウト",
        "strategy_state_value_liquidity_trap_label": "流動性トラップ",
        "strategy_state_value_mean_reversion_label": "平均回帰",
        "strategy_state_value_momentum_probe_label": "モメンタム探索",

        "ai_runtime_mode": "AI実行モード",
        "ai_runtime_mode_local": "local",
        "ai_runtime_mode_external": "external",
        "ai_conversation_clear": "履歴クリア",
        "ai_conversation_clear_done": "会話履歴をクリアしました。",

        "ai_runtime_external_disabled": "external AI モードは無効です",
        "ai_runtime_external_url_missing": "external AI の URL が未設定です",
        "ai_runtime_external_http_error": "external AI HTTP エラー",
        "ai_runtime_external_network_error": "external AI 接続エラー",
        "ai_runtime_external_timeout": "external AI の応答がタイムアウトしました",
        "ai_runtime_external_bad_response": "external AI から不正な JSON が返りました",
        "ai_runtime_external_answer_missing": "external AI 応答に有効な answer がありません",
        "ai_runtime_fallback_prefix": "external AI 失敗のため local にフォールバック",
        "ai_runtime_source": "実行ソース",

        "ai_memory_title": "市場状態メモリ",
        "ai_memory_empty": "市場状態メモリはまだありません。",
        "ai_memory_trend_improving": "改善",
        "ai_memory_trend_worsening": "悪化",
        "ai_memory_trend_stable": "安定",
        "ai_memory_spread_change": "スプレッド変化",
        "ai_memory_imbalance_change": "板バランス変化",
        "ai_memory_delta_change": "約定デルタ変化",
        "ai_memory_wall_ratio_change": "壁比率変化",
        "ai_memory_persistent_hint": "市場状態メモリは JSONL に保存され、UI再読込後も保持されます。",

        "execution_feed_status_empty": "空",
        "execution_feed_status_alert": "警戒",
        "execution_feed_status_busy": "高負荷",
        "execution_feed_status_throttled": "抑制中",
        "execution_feed_status_normal": "正常",

        "ai_conversation_intent": "質問意図",
        "ai_conversation_style": "応答スタイル",
        "ai_conversation_intent_explain": "市場説明",
        "ai_conversation_intent_decide": "判断補助",
        "ai_conversation_intent_risk": "リスク確認",
        "ai_conversation_intent_wall": "壁分析",
        "ai_conversation_style_concise": "簡潔",
        "ai_conversation_style_normal": "通常",
        "ai_conversation_style_deep": "詳細",
        "ai_conversation_effective_prompt": "実効プロンプト",

        "research_memory_delta_from_prev": "前回差分",
        "research_memory_regime_hint": "研究ヒント",
        "research_memory_hint_trend": "方向性バイアスが拡大しています。",
        "research_memory_hint_range": "バイアスは混在しておりレンジ寄りです。",
        "research_latency_by_topic": "topic別レイテンシ",
        "research_latency_topic": "topic",
        "research_latency_topic_avg": "平均レイテンシ(ms)",
        "research_latency_topic_count": "件数",
        "research_storage_total_size": "合計サイズ(MB)",

        "warroom_header_title": "War Room Situation",
        "warroom_header_missing_data": "War Room ヘッダーに必要なデータがありません。",
        "warroom_header_regime": "市場レジーム",
        "warroom_header_spread_state": "スプレッド状態",
        "warroom_header_pressure": "圧力",
        "warroom_header_trade_flow": "約定フロー",
        "warroom_header_ai_decision": "AI判断",
        "warroom_header_risk": "リスク",

        "ai_reasoning_title": "AI Reasoning",
        "ai_reasoning_missing_data": "AI Reasoning に必要なデータがありません。",
        "ai_reasoning_reasons": "AI がそう考える理由",
        "ai_reasoning_conclusion": "結論",
        "ai_reasoning_headline_long": "AIはロング継続を支える条件が揃いつつあると見ています。",
        "ai_reasoning_headline_short": "AIはショート継続を支える条件が揃いつつあると見ています。",
        "ai_reasoning_headline_buy_pressure": "AIは買い圧力の形成を見ています。",
        "ai_reasoning_headline_sell_pressure": "AIは売り圧力の形成を見ています。",
        "ai_reasoning_headline_wait": "AIは条件が混在しているため慎重姿勢です。",
        "ai_reasoning_reason_spread_wide": "スプレッドが広く、執行品質は不安定寄りです。",
        "ai_reasoning_reason_spread_tight": "スプレッドが狭く、執行条件は比較的良好です。",
        "ai_reasoning_reason_spread_normal": "スプレッドは通常レンジです。",
        "ai_reasoning_reason_bid_bias": "板は買い側優勢です。",
        "ai_reasoning_reason_ask_bias": "板は売り側優勢です。",
        "ai_reasoning_reason_balance_mixed": "板バランスは混在しています。",
        "ai_reasoning_reason_buy_flow": "約定フローは買い寄りです。",
        "ai_reasoning_reason_sell_flow": "約定フローは売り寄りです。",
        "ai_reasoning_reason_flow_mixed": "約定フローはまだ混在しています。",
        "ai_reasoning_reason_bid_wall": "買い壁が見えており、下方向の吸収余地があります。",
        "ai_reasoning_reason_ask_wall": "売り壁が見えており、上方向の継続が抑えられる可能性があります。",
        "ai_reasoning_conclusion_long_watch": "ロング継続を監視しつつ、持続確認を優先します。",
        "ai_reasoning_conclusion_short_watch": "ショート継続を監視しつつ、持続確認を優先します。",
        "ai_reasoning_conclusion_wall_risk": "壁の偏りが強く、トラップリスクに注意が必要です。",
        "ai_reasoning_conclusion_wait": "現状はまだ明確な確証待ちが妥当です。",

        "warroom_alert_empty": "現時点で重要アラートはありません。",
        "warroom_alert_caption": "アラートは replay / research artifact と直近監査レイテンシを基に生成しています。",
        "ui_label_guide": "ガイド",
        "ui_label_overview": "概要",
        "ui_label_operator_support": "運用補助",
        "ui_label_primary_live": "主要ライブ監視",
        "ui_label_ai_diagnostics": "AI診断",
        "ui_label_unified_supervisor": "Unified Supervisor",
        "ui_label_rate_control": "Rate Control",
        "ui_label_origin_continuity": "Origin Continuity",
        "ui_label_origin_continuity_audit": "Origin Continuity Audit",
        "ui_label_collector_runtime_state": "Collector Runtime State",
        "ui_label_raw_origin_status_json": "Raw origin_status JSON",
        "ui_label_ws_continuity_origin_status": "WS Continuity (origin_status)",
        "ui_label_daemon_supervisor_health": "Daemon / Supervisor Health",
        "ui_label_raw_rate_state_json": "Raw Rate State JSON",
        "ui_label_archive_retention_diagnostics": "Archive / Retention Diagnostics",
        "ui_label_archive_latest_copy": "Latest Copy 5",
        "ui_label_archive_latest_delete": "Latest Delete 5",
        "ui_label_archive_hot_remaining": "Hot D drive remaining data files (latest 50)",
        "collector_metric_continuity_status": "継続状態",
        "collector_metric_ws_state": "WS状態",
        "collector_metric_snapshot_to_live_ms": "Snapshot→LIVE (ms)",
        "collector_metric_resync_occurred": "Resync発生",
        "collector_metric_dropped_pre_snapshot_deltas": "事前スナップショット破棄差分",
        "collector_metric_origin_age_sec": "Origin経過秒",
        "collector_metric_gap_detected": "Gap検知",
        "collector_metric_resync_started": "Resync開始",
        "collector_metric_resync_completed": "Resync完了",
        "collector_metric_resync_complete_ratio": "Resync完了率",
        "collector_metric_copy_mode": "コピー方式",
        "collector_metric_gc_mode": "GC方式",
        "collector_metric_gc_enabled": "GC有効",
        "collector_metric_gc_dry_run": "GCドライラン",
        "collector_metric_remaining_hot_files": "残存Hotファイル数",
        "collector_metric_supervisor_mode": "Supervisor状態",
        "collector_metric_pending_request": "保留リクエスト",
        "collector_metric_supervisor_uptime_sec": "Supervisor稼働秒",
        "collector_metric_rate_posture": "Rate姿勢",
        "collector_metric_recent_429": "直近429",
        "collector_metric_rate_summary": "Rate要約",
        "collector_metric_wait_ms": "待機(ms)",
        "collector_metric_util_ratio": "利用率",
        "collector_metric_recovery": "回復状態",
        "collector_metric_status_freshness": "Status鮮度",
        "collector_metric_status_age_sec": "Status経過秒",
        "collector_metric_origin_ws_state": "Origin WS状態",
        "collector_metric_origin_snapshot_to_live_ms": "Origin Snapshot→LIVE (ms)",
        "collector_metric_origin_pre_snapshot_drops": "Origin事前スナップショット破棄数",
        "collector_msg_watchdog_not_running": "watchdog は RUNNING ではありません。request file は書けますが、restart が実行されない可能性があります。",
        "collector_msg_restart_pending": "restart request はすでに pending です。watchdog が消費するまで再発行は待ってください。",
        "collector_msg_supervisor_status_unavailable": "unified supervisor status を利用できません",
        "collector_msg_rate_state_unavailable": "rate_state.json を利用できません",
        "collector_msg_recent_429_detected": "直近 429 を検知",
        "collector_msg_rate_posture_normal": "rate posture は正常",
        "collector_msg_rate_control_engaged": "rate control が作動中",
        "collector_msg_origin_status_unavailable": "origin_status.json を利用できません",
        "collector_msg_daemon_health_unavailable": "daemon health state を利用できません",
        "collector_msg_latest_copy_unavailable": "latest copy history を利用できません",
        "collector_msg_latest_delete_unavailable": "latest delete history を利用できません",
        "collector_msg_hot_remaining_unavailable": "hot remaining data files を利用できません",
        "collector_msg_status_origin_unavailable": "status.json origin_continuity を利用できません",
        "collector_caption_reason_line": "reason={reason} / live_mode={live_mode} / health={health} / daemon={daemon} / cycle_last_sequence_id={sequence_id}",
        "collector_caption_supervisor_line": "supervisor_mode={mode} / last_action={last_action} / last_error={last_error}",
        "collector_caption_pending_request_line": "pending_request={action} / requested_by={requested_by} / reason={reason}",
        "collector_caption_daemon_stop_line": "daemon_stop_request={action} / requested_by={requested_by}",
        "collector_caption_age_line": "age status={status_age} / health={health_age} / daemon={daemon_age} / checkpoint={checkpoint_age}",
        "collector_caption_state_dir_line": "state_dir={path}",
        "collector_caption_ui_roots_line": "ui_data_root={data_root} / ui_logs_root={logs_root} / ui_market_state_root={market_state_root}",
        "collector_caption_archive_started_line": "archive_started_at={started_at} / copy_last_scan_ts={copy_last_scan_ts} / gc_last_scan_ts={gc_last_scan_ts}",
        "collector_caption_archive_counts_line": "copy_last_plan_count={copy_plan_count} / copy_last_copied_files={copy_copied_files} / gc_last_plan_count={gc_plan_count} / gc_last_deleted_files={gc_deleted_files}",
        "collector_caption_archive_audit_path_line": "archive_audit_path={audit_path}",
        "ui_slot_diagnostics_title": "UI Slot Diagnostics",
        "ui_slot_diagnostics_health_caption": "health ページの slot registry / refresh_mode と priority の試験表示",
        "ui_slot_registry_empty_health": "health の slot registry は空です",
        "health_label_range_selector": "表示レンジ",
        "health_range_1h": "1時間",
        "health_range_24h": "24時間",
        "health_range_1w": "1週間",
        "health_event_ws_exec_started": "ws executions 開始",
        "health_event_ws_exec_connected": "ws executions 接続",
        "health_event_ws_exec_reconnected": "ws executions 再接続",
        "health_event_ws_exec_message_received": "ws executions メッセージ受信",
        "health_event_ws_exec_message_skipped": "ws executions メッセージスキップ",
        "health_event_ws_exec_meta": "ws executions メタイベント",
        "health_event_ws_exec_trade_written": "ws executions trade 書き込み",

    },
}

for _lang in ("en", "ja"):
    TEXTS.setdefault(_lang, {})
    TEXTS[_lang].update(SPLIT_TEXTS.get(_lang, {}))

def get_text(lang: str, key: str) -> str:

    if lang not in TEXTS:
        lang = "en"

    return TEXTS[lang].get(key, key)